### ISSUE TITLE
crash when changing modes

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#101]
Was in normal, switched to elevation and clicked delete map and apply, it booted me out. logged back into the game and the exposed terrain was still normal, while newly loaded terrain had elevation color. I went back into the menu and switched back to normal. The option for a land use file did not appear. I clicked the same button and the game crashed.

looks like we need to add some basic null value cases

2016-03-09 21:06:28: ERROR[main]: ServerError: Lua: Runtime error from mod 'real
terrain' in callback ScriptApiPlayer::on_playerReceiveFields(): I:\Minetest\bin\
..\mods\realterrain/height_pixels.lua:259: attempt to compare nil with number
2016-03-09 21:06:28: ERROR[main]: stack traceback:
2016-03-09 21:06:28: ERROR[main]:       I:\Minetest\bin\..\mods\realterrain/heig
ht_pixels.lua:259: in function 'build_heightmap'
2016-03-09 21:06:28: ERROR[main]:       I:\Minetest\bin\..\mods\realterrain/heig
ht_pixels.lua:399: in function 'get_surface'
2016-03-09 21:06:28: ERROR[main]:       I:\Minetest\bin\..\mods\realterrain/cont
roller.lua:113: in function 'show_rc_form'
2016-03-09 21:06:28: ERROR[main]:       I:\Minetest\bin\..\mods\realterrain/cont
roller.lua:616: in function <I:\Minetest\bin\..\mods\realterrain/controller.lua:
530>
2016-03-09 21:06:28: ERROR[main]:       I:\Minetest\bin\..\builtin\game\register
.lua:355: in function <I:\Minetest\bin\..\builtin\game\register.lua:335>

**Comment by bobombolo** [comment]
the delete button is ... experimental. i guess it should be removed. usually in my tests it manages to delete the map.sqlite file but it sounds like in your case it didn't, might be a permissions thing, maybe windows won't let the file delete. at any rate, the game crashes if the map.sqlite file is deleted before the game exits, which is often. not sure how to deal with this... manually deleting the map.sqlite file in the world folder might be the only solution. i have asked the devs about a callback that isn't triggered until the game is for sure exited to menu, but there isn't one. also tried adding a delay but sometimes the game takes several seconds to exit. to date i still manually delete... see #19 

the field for landuse file is removed when in normal mode.

this crash is probably a consequence of a corrupted settings file due to the first crash. the "delete" button might just have to be removed.

**Comment by Tank-ACiD** [comment]
This is happening on other modes also, even when deleting the map.sqlite file

I set mode to slope, clicked apply, crash. kicked me out to menu. i deleted file, entered game, crash

2016-03-10 23:18:03: ERROR[main]: ServerError: Lua: Runtime error from mod 'real
terrain' in callback ScriptApiEnv::environment_OnGenerated(): I:\Minetest\bin\..
\mods\realterrain/mapgen.lua:190: attempt to perform arithmetic on field 'f' (a
nil value)
2016-03-10 23:18:03: ERROR[main]: stack traceback:
2016-03-10 23:18:03: ERROR[main]:       I:\Minetest\bin\..\mods\realterrain/mapg
en.lua:190: in function 'get_slope'
2016-03-10 23:18:03: ERROR[main]:       I:\Minetest\bin\..\mods\realterrain/mapg
en.lua:505: in function 'generate'
2016-03-10 23:18:03: ERROR[main]:       I:\Minetest\bin\..\mods\realterrain\init
.lua:297: in function <I:\Minetest\bin\..\mods\realterrain\init.lua:296>
2016-03-10 23:18:03: ERROR[main]:       I:\Minetest\bin\..\builtin\game\register
.lua:355: in function <I:\Minetest\bin\..\builtin\game\register.lua:335>

**Comment by bobombolo** [comment]
just to be clear:
are you running any other mods at the same time?
is this stacktrace from the first crash or the second one after you renter the game or are they the same?

**Comment by bobombolo** [comment]
oh and my mistake normal mode should have a landuse field of course. i am trying to recreate this...

**Comment by bobombolo** [comment]
i have recreated this and am debugging now...

**Comment by bobombolo** [comment]
something has broken with the moving window... mapgen.lua line 476, we are not entering this loop to build the neighborhood.

**Comment by bobombolo** [comment]
ok line 476 of mapgen.lua needs to be changed from an ipairs() to pairs()

this was a minor error from gael's refactoring, not a null value issue

please test this fix.

**Comment by Tank-ACiD** [comment]
will do. got kiddo for 5 days will try and sneak some time in.

**Comment by Gael-de-Sailly** [comment]
That's from my changes, I'm sorry. I've not seen that the `neighborhood` variable had litteral indexes so we can't use `ipairs`. I've just changed that in another place too, and moved `realterrain.neighborhood` into `mapgen.lua` since it's only used in this file.
See #102.
