### ISSUE TITLE
image processing for core

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#103]
this is a place to discuss the writing of a pull request for core to give the lua modding api some methods to open image file handles, get pixel values and possibly close image file handles. core developers have stated that this would be included in core if written well and if it stays simple.

files to alter in core should be:
https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_util.h
https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_util.cpp

the methods we will need:
*** open an image file as a handle returning the handle reference (?), or return an error if unable. this should use the following irrlicht API methods:
 irr::video::IImageLoader::isALoadableFileExtension()
 irr::video::IImageLoader::loadImage()
see http://irrlicht.sourceforge.net/docu/classirr_1_1video_1_1_i_image_loader.html

*** get pixel value (as a color object or simply a table or a,r,g,b) given row/column using the following irrlicht method:
 irr::video::IImage::getPixel()
see: http://irrlicht.sourceforge.net/docu/classirr_1_1video_1_1_i_image.html
and: http://irrlicht.sourceforge.net/docu/classirr_1_1video_1_1_s_color.html

note: there is also a float color class:
http://irrlicht.sourceforge.net/docu/classirr_1_1video_1_1_s_colorf.html

*** Image metadata such as width, height, pixel bit_depth and color_format (see comment below)
see:  irr::video::IImage::getBitsPerPixel() since most DEMs are 16bit greyscale
color format: irr::video::IImage::getColorFormat()
dimensions:  irr::video::IImage::getDimension()

questions:

the color classes both seem to support only unsigned channel values so we still are not able to use negative elevations in DEMs?

is the file handle destroyed every time or does it persist for multiple get_pixel() calls? is there overhead to creating the Iimage object? if so perhaps we need a method that gets many pixels at once, such as get_pixels() which retrieves the footprint for the 80x80 mapchunk...

**Comment by bobombolo** [comment]
actually the method getBitsPerPixel might also be important, or at least useful. many DEMs are 16bit (most, all) greyscale. 
see:  irr::video::IImage::getBitsPerPixel()
also, reporting other metadata about the image would be nice such as:
color format: irr::video::IImage::getColorFormat()
and the dimensions of the raster:  irr::video::IImage::getDimension()

**Comment by Gael-de-Sailly** [comment]
This should be an issue in Minetest's main repo.

**Comment by bobombolo** [comment]
yes i just wanted to flesh it out before i create an issue there so i don't look stupid.

**Comment by bobombolo** [comment]
actually i wonder if this should go in the util section or be its own section:
src/script/lua_api/l_image.h
src/script/lua_api/l_image.cpp

**Comment by bobombolo** [comment]
moved to https://github.com/minetest/minetest/issues/3869
