### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#15]
currently garbage could be entered into the form and it would crash the game

**Comment by bobombolo** [comment]
this has been greatly aided by the use of dropdowns and image buttons wherever possible. the last few things to check are the numerical entries

**Comment by bobombolo** [comment]
some validation improvements made recently regarding raster and mode selection (still none for the numbers)

**Comment by bobombolo** [comment]
![screenshot_20151128_172841](https://cloud.githubusercontent.com/assets/12679496/11454885/7abec818-95f5-11e5-8203-0b77726bfdfa.png)

**Comment by bobombolo** [comment]
need to add form validation for "imageoverlay" and "bandoverlay" modes?

**Comment by bobombolo** [comment]
took a step forward and backward with form validation today. by updating the form based on the current mode I have removed the check for having rasters selected for modes that need them. this is actually better though. missing rasters simply report zero. eventually validation will be a priority, at least number fields... informative text explaining what rasters are required is probably how I will handle that issue. it is up to the user to say, "hey my world is flat" or "there is no biomes"...

**Comment by Tank-ACiD** [comment]
Yeah, I'll try to focus on this aspect this month

**Comment by bobombolo** [comment]
form validation implemented. nicely.
![screenshot_20151212_210551](https://cloud.githubusercontent.com/assets/12679496/11765611/2a4d5898-a114-11e5-8fc5-796abf52c6b3.png)
