### ISSUE TITLE
access GDAL gis functions (python)

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#17]
LUA Python bridge might accomplish this:
https://labix.org/lunatic-python
this would allow us to use regular .lyr vector files as cover files and orientate layers via real-world coordinates, as well as translate in game positions to real world coordinates... among many many other things (farming out raster analysis to GRASS, output to .lyr files, etc.)

**Comment by bobombolo** [comment]
another option is to write an adapter using io.popen() to pass python commands and retrieve results

**Comment by bobombolo** [comment]
i have added lunatic lib to the mod, it seems to load. now to try some python calls using <pre>python.execute("foo = 'bar'")</pre> as per:

https://labix.org/lunatic-python#head-f85d4ac1416491b93f8d7dbd118101ccb750b88f-2

**Comment by bobombolo** [comment]
have a build issue in ubuntu might be related to this: https://github.com/bastibe/lunatic-python/issues/1

**Comment by bobombolo** [comment]
https://github.com/bastibe/lunatic-python/issues/35

**Comment by bobombolo** [comment]
https://pypi.python.org/pypi/lupa
lupa may be a better bet than lunatic

**Comment by bobombolo** [comment]
also lupy
http://lupy.readthedocs.org/en/latest/intro.html
but this may be more for lua in python?

**Comment by bobombolo** [comment]
OK so I was able to get lunatic to load in ubuntu and the maintainer says that he builds it in windows with Cmake and it works fine. I think this might be the next stage for GIS functionality from GRASS.

**Comment by bobombolo** [comment]
the latest push includes the first few lines of code to get lunatic loading grass in ubuntu. we need to make a platform-sensitive loader that works in windows too.

**Comment by Tank-ACiD** [comment]
Will try to get it working. busy week with candidate interviews and
prepping a presentation on this for the 12th

**Comment by bobombolo** [comment]
we may not want to use the grass python library, we may want to use GDAL:

https://pypi.python.org/pypi/GDAL/

**Comment by bobombolo** [comment]
the next step in this issue is to switch from using magick/imlib2 to get pixel value to using gdal to get elevation value based on coordinates.
http://gis.stackexchange.com/questions/29632/raster-how-to-get-elevation-at-lat-long-using-python
commandline calls to gdalinfo might also be more productive than calls to magick's IDENTIFY:
here is a starting point for GDAL
https://pcjericks.github.io/py-gdalogr-cookbook/

**Comment by bobombolo** [comment]
need help executing python inside lua: https://labix.org/lunatic-python#head-f85d4ac1416491b93f8d7dbd118101ccb750b88f-2

want to do:
<pre>
py.execute("from osgeo import gdal")
py.execute("gtif = gdal.Open( '"..RASTERS..realterrain.settings.filedem.."' )")
print(py.eval("print gtif.GetMetadata()"))
</pre>

or something like that

**Comment by Tank-ACiD** [comment]
I think the py execute might need to follow python syntax? I'll take a look
at gdal this weekend f I have time. I just received a few recent articles
on this topic that I need to digest and summarize.

**Comment by bobombolo** [comment]
actually this works:
<pre>
py.execute("from osgeo import gdal")
py.execute("gtif = gdal.Open( '"..RASTERS..realterrain.settings.filedem.."' )")
local pyresults = py.eval("gtif.GetMetadata()")
print(pyresults)
</pre>
so this door is now open to us.

**Comment by bobombolo** [comment]
using the Python Imaging Library through lunatic-python I am able to generate the world as fast as any other method. also the PIL allows for direct access of 16-bit values (though I am having an issue with that at the moment) and it also will tell you the bit-depth or at least the mode, but that doesn't matter because it directly handles 16 bit values. lunatic might be the way to reduce our dependencies down to just one library, albeit a tricky one to install (requires a make install) and the python libraries we need but might already have (PIL, numpy, GDAL)

[DEM] 257 ms  mapchunk (0, 2, 0)
[DEM] 276 ms  mapchunk (0, 3, 0)
[DEM] 535 ms  mapchunk (1, 2, -1)
[DEM] 332 ms  mapchunk (1, 2, 0)
[DEM] 456 ms  mapchunk (0, 2, -1)
[DEM] 811 ms  mapchunk (1, 3, -1)
[DEM] 724 ms  mapchunk (1, 3, 0)
[DEM] 581 ms  mapchunk (0, 3, -1)

**Comment by bobombolo** [comment]
16 bit issue was not an issue. everything works fine

**Comment by bobombolo** [comment]
so it is quite a bit slower to use PIL to get pixels but on the plus side it handles 16 bit without manual setting the bit depth, and it handles Ryan's arcGIS exported 16 bit dem out of the box

**Comment by bobombolo** [comment]
at any rate we have shown that we can use python in realterrain, which opens gdal, grass, arc.py etc. at this time the mod does not create any temporary files, but now we could import shapefiles and convert them to raster, or perform slope or other analysis on the entire dem and create an intermediate file.

**Comment by Tank-ACiD** [comment]
auto bit handling is good, but if we can add a few lines of code with an
added lib to autodetect resulting in better performance... that might be
preferred. Because in the end-user experience, they won't care how we
handle bit depths but they will care about lag.

**Comment by bobombolo** [comment]
well so far the PIL is the best way I see to get the image "mode" which will tell us if it is 16 bit, and it is near-instant, so it is another dependency but gives us that auto-detect.

**Comment by bobombolo** [comment]
another thing that is faster is the initial loading of the map, which usually pauses on the loading of the image by magick or imlib2, it is instead near-instant, which might mean that we can open larger files. I have had the system choke on that initial load with large files like your dem a few times here and there. btw I am running a 9gb ram AMD A8-5500 APU with Radeon(tm) HD Graphics × 4 and an SSD drive.

**Comment by bobombolo** [comment]
anyway you can try it in the USGS branch. I am not going to leave it like this but i might factor it in as an option. have you had any luck building lunatic yet?

**Comment by Tank-ACiD** [comment]
not yet, building anything on windows is a big pain

**Comment by bobombolo** [comment]
do you use Cmake? the maintainer of lunatic says it works fine for him.

**Comment by bobombolo** [comment]
about the initial load I think that because the initial load is happening in the background by the python interpreter and so it is still taking some time but not stalling lua, this is evidenced by the fact that the first chunk takes longer to generate:

[DEM] 5083 ms  mapchunk (3, 6, -1)

probably because it is still loading the dem

**Comment by bobombolo** [comment]
https://github.com/bastibe/lunatic-python/issues/23

**Comment by bobombolo** [comment]
just trying learn GDAL a little. want to be able to do the following:

for each mapchunk, generate an output raster that can be loaded into the mapgen heightmap, then destroy the hieghtmap and move to the next chunk.

for now just creating a raster for the whole input raster, and testing with gdal.ComputeProximity() but the output file is blank.

http://nullege.com/codes/show/src@g@d@GDAL-1.10.0@scripts@gdal_proximity.py/179/gdal.ComputeProximity

I have done:

<pre>
srcfile = gdal.Open("points.tif")
srcband = srcfile.GetRasterBand(1)
drv = gdal.GetDriverByName("GTiff")
dst_rastername = "output.tif"
dst_ds = drv.Create(dst_rastername, srcfile.RasterXSize, srcfile.RasterYSize)
dst_band = dst_ds.GetRasterBand(1)
gdal.ComputeProximity(srcband, dst_band)
</pre>

anyway just need to get one sample processing working then I can automate the process per chunk...

**Comment by bobombolo** [comment]
actually looking in my trash I apparently had it working at one point:
![points](https://cloud.githubusercontent.com/assets/12679496/11319512/956cf3aa-902e-11e5-8916-28a4a229ce74.png)
![output](https://cloud.githubusercontent.com/assets/12679496/11319513/98f2623a-902e-11e5-8925-3b7a3bee8436.png)

**Comment by bobombolo** [comment]
but i can't recreate that. haha

**Comment by bobombolo** [comment]
proper results appear in my trash, but the actual output file is empty! weird...

**Comment by bobombolo** [comment]
haha, ok I had to do quit() in the python interpreter. need to figure out how to close out the file or something. so this is working. now i need to clip the source raster first, to handle mapchunk by mapchunk

an interesting thing to do might be to do vertical planes for "proximity" so that we are using the 3D nature of our environment

**Comment by Tank-ACiD** [comment]
of course, how it always goes! I'll have a bit of time to look at things
mon-tues

**Comment by bobombolo** [comment]
so the complete set of operations is:
<pre>
import gdal
srcfile = gdal.Open("points.tif")
srcband = srcfile.GetRasterBand(1)
drv = gdal.GetDriverByName("GTiff")
dst_rastername = "output.tif"
dst_ds = drv.Create(dst_rastername, srcfile.RasterXSize, srcfile.RasterYSize)
dst_band = dst_ds.GetRasterBand(1)
gdal.ComputeProximity(srcband, dst_band)
dst_ds = None
</pre>

**Comment by bobombolo** [comment]
i wonder if we manage to build the lunatic-python on windows if we can just use those binaries and include them in the mod somehow, adding the path to the mod folder to the windows environment or the makefile?
alternatively, the files for most of these GDAL processing operations are also available as command line utilities, including proximity.py, so we might want to go that route. actually that makes more sense and would only require a functioning python interpreter and the libraries present in the system rather than building lunatic-python and having everything linked properly... it is not an issue of speed like it was for imageMagick command line calls because that is pixel-for-pixel and gets too slow, whereas here we are processing an entire raster or a mapchunk of a raster and then accessing it pixel-by-pixel later.

**Comment by bobombolo** [comment]
perhaps a series of options is required:

python = true, false, cli, lunatic
pixel_access = imlib2, magick, pli --Python Imaging Library only available in python = lunatic mode
luarocks = true, false

and all library loading will happen accordingly

of course the best would be to just have the optimal configuration easy to set up...

the imagesize library is just a port of the PIL

**Comment by bobombolo** [comment]
also it is tempting, for the average mod user, to re-include my original 8-bit tiff implementation that handled pixel access in-mod

**Comment by bobombolo** [comment]
things like viewsheds and watersheds might need more than GDAL, like GRASS

**Comment by bobombolo** [comment]
this can be part of the libraries discussion #45

**Comment by bobombolo** [comment]
doing proximity gdal from command line script does not output a valid image out of the box, but the python interpreter method works... on the mv roads file the process takes 30seconds on my system.
