### ISSUE TITLE
ores

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#18]
for game playability there should be a probability table for different ores and they can be randomly placed in various strata.

**Comment by bobombolo** [comment]
prepare for a soils layer

**Comment by bobombolo** [comment]
or have biomes also have several dominant ores/lava/voids/water probabilities

**Comment by bobombolo** [comment]
is there a popular classification system for soil types that we could use for our underground ore dispersion? i can't imagine one that won't require another layer file. large maps are already crashing from two or three files. four might be pushing it. i think for now i might just create a probability table for ores that is biome-independent just for playability

![screenshot_20151129_003535](https://cloud.githubusercontent.com/assets/12679496/11460949/4cbcc150-96ad-11e5-8a21-9bf85fb56fea.png)

which is pretty boring. i might make it depth-dependent, but biome + depth dependent might be cool too.

**Comment by Tank-ACiD** [comment]
ore generation is whatever to me, not really interested for scientific
applications but for play-ability yes, we could come up with some
definitions of ore types per soil type. USGS has soil classification

http://ngmdb.usgs.gov/lex-bin/resources.pl

pg 1577 describes the soil profile classification

but I don't see geological types like, shale, sandstone, limestone, granite
etc.. this page is intresting

http://www.seafriends.org.nz/enviro/soil/rocktbl2.htm

**Comment by bobombolo** [comment]
should look at the code here for ores:
https://forum.minetest.net/viewtopic.php?f=9&t=11430

specifically the use of minetest.register_ore -- i was totally unaware of this callback

also maybe take some of the trees and plants from that mod?

**Comment by bobombolo** [comment]
http://dev.minetest.net/minetest.register_ore

**Comment by bobombolo** [comment]
![screenshot_20151222_195634](https://cloud.githubusercontent.com/assets/12679496/11970810/3d5d4a90-a8e6-11e5-876d-031e03e4c39d.png)

**Comment by bobombolo** [comment]
OK switched to just using the default ores.

![screenshot_20151222_204703](https://cloud.githubusercontent.com/assets/12679496/11971158/5cd37ca8-a8ed-11e5-9047-08db41d27bbd.png)
