### ISSUE TITLE
test luafilesystem alternative in windows

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#21]
this works in ubuntu:
<pre>
function dirLookup(dir)
    local p = io.popen('find "'..dir..'" -type f')  --Open directory look for files, save data in p. By giving '-type f' as parameter, it returns all files.     
    for file in p:lines() do                         --Loop through all files
        print(file)       
    end
 end
dirLookup(MODPATH.."/dem/")
</pre>
if it works in windows we can remove luafilesystem as a depends

**Comment by bobombolo** [comment]
this has been pushed to master, needs to be tested on windows. this is the current state of the settings tool form:

![screenshot_20151025_071817](https://cloud.githubusercontent.com/assets/12679496/10716053/98fdf0ec-7ae8-11e5-8da7-470b839fdf40.png)

**Comment by Tank-ACiD** [comment]
does not work in windows no default is displayed, no drop down is populated.

**Comment by Tank-ACiD** [comment]
message to system window:
File not found - -TYPE
File not found - F

I'll play around with the code and see what I can get to work.

**Comment by bobombolo** [comment]
ok so it's either a library or it's a function that only works with nix systems... I will look for a function that works in windows and then a function that detects nix vs windows and the mod can select between them. i think it would be nice to have those dropdowns for files such as treetypes and buildings later... still it is a minor feature and we could just leave them as text fields that get validated...
at any rate you can always hand-edit the defaults in the mod... never touching the settings tool...

**Comment by Tank-ACiD** [comment]
this works...

function realterrain.list_images()
local dir = MODPATH .. "/dem/"
local i, list, popen = 0, {}, io.popen
for filename in popen('dir "'..dir..'" /b'):lines() do
        --Open directory look for files, loop through all files

        i = i + 1
list[i] = filename
end
return list
end

**Comment by Tank-ACiD** [comment]
currently trying to figure out syntax to request only *.png *.tif etc. may
have to invoke multiple dir calls to get each file type appended to the
list.

for multiple OS compatibility we may need to first detect OS and run
appropriate funtion

**Comment by bobombolo** [comment]
i'm using the popen method right now, it works with some issues that I am working through.
as for filtering image types, that is why i was using magick to open each file to see if it is an image, which is the best way, ultimately since extensions can't be trusted.  as i see it there should only be image files in the dem folder anyway

**Comment by Tank-ACiD** [comment]
I agree extensions can't be trusted, but... they are right 99.99% of the
time. I would propose a validation check to the selected raster before
processing, letting the user select whatever file they want.

As you saw in my raster collection, there are many files associated with a
geo-raster. If a GIS user is exporting to the dem folder like I have been,
it is quickly populated with the associated files, junk files that crappy
GIS software like ArcMap doesn't remove, temporary OS files, etc. While,
ideally, the user should be manually moving a raster into the dem folder
(could we rename it to raster since it's much more descriptive than just
holding dem?) it's expected that they will purposefully or inadvertently
populate the dir with garbage.

**Comment by bobombolo** [comment]
sting.sub would be the way to deal with extensions...
yeah maybe we will just leave this as a text field for now...

i am going to set aside a day to deal with form validation this week. that way we can use magick to test any typed filename and if it doesn't work then the form spits up.

yes i agree all the extra metadata files generated by gis software should be filtered out...

so yeah, i guess we will just set that back to a text field and be done with platform differences and an extra library dependency that has issues in windows...

**Comment by Tank-ACiD** [comment]
don't know if this syntax is correct yet so trat a pseudocode (Windows)

function realterrain.list_images()
local dir = MODPATH .. "/dem"
local rtypes = {}
rtypes[1] = {".png"}
rtypes[2] = {".tif"}
local i, list, extension, popen = 0, {}, io.popen
--Open directory look for files, loop through all files
for filename in popen('dir "'..dir..'" /b'):lines() do

for extension in next, rtypes do
if string.sub(filename,extension) then
   i = i + 1
list[i] = filename
end
end
end
return list
end

**Comment by bobombolo** [comment]
i have removed the dropdowns for now. i have renamed the dem folder to rasters.

**Comment by Tank-ACiD** [comment]
reopen? i've almost got cross platform dropdown working... not optimized
code but working code

**Comment by Tank-ACiD** [comment]
This works in Windows, does it work in Unix. (screw mac ..haha no should be
same as windows)

function realterrain.list_images()
local dir = MODPATH .. "/dem/"
local rtypes = {".png", ".tif"}
if package.config:sub(1,1) == "/" then
--Unix
local list = {}
--Open directory look for files, save data in p. By giving '-type f' as
parameter, it returns all files.
local p = io.popen('find "'..RASTERS..'" -type f')
--Loop through all files
for file in p:lines() do
file = string.sub(file, #RASTERS + 1)
for j, extension in ipairs(rtypes) do
if string.find(file, extension, -4) ~= nil then
table.insert(list, file)
end
end
end
return list
else
--Windows
local i, list, popen = 0, {}, io.popen
--Open directory look for files, loop through all files
for filename in popen('dir "'..dir..'" /b'):lines() do
for j, extension in ipairs(rtypes) do
if string.find(filename, extension, -4) ~= nil then
i = i + 1
list[i] = filename
end
end
end
return list
end
end

**Comment by bobombolo** [comment]
on getting libraries working more seamlessly. we could include them in the mod itself if we can figure out the paths issue for ie.require. there seems to be a way to add paths in-mod to facilitate that, something like:

package.path = (MP.."/lib/pngLua/?.lua;"
		..MP.."/lib/pngLua/?/init.lua;"
		..package.path)
and there is always the option of replacing "require" with "dofile" as I did with imagesize in early versions of this mod, a lib which, incidentally, was able to detect imageness of files and their type based on header, which means it is low-memory usage unlike using magick.load_image() like i tried yesterday which crashed my system.

**Comment by bobombolo** [comment]
i have made some changes to this code, can you test it in windows? it should now show only image files and no others.

**Comment by bobombolo** [comment]
i need a windows test for all the changes over the last few days. mostly in the form menus

**Comment by Tank-ACiD** [comment]
will do. Going to remove all files associated with previous mod versions and start from scratch, modifying/rewriting the Windows based install notes. I want to make sure dependencies are loading as you expect them and not how they may still persist in my environment.

**Comment by Tank-ACiD** [comment]
Line 17 ... should the string be something not equal to "imagesize" ?

**Comment by bobombolo** [comment]
it should be "python" and then an error is thrown. I think we need to build something, so this might not be an easy thing to deploy...

**Comment by bobombolo** [comment]
see issue #17 for the python discussion

**Comment by bobombolo** [comment]
sounds like the basic mod is working in windows
