### ISSUE TITLE
listing images is very slow (disabled)

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#22]
currently all files in the dem folder will be listed in the settings tool as potential layer files, which is due to the fact that using the magick.load_image() method is extremely slow when iterating through all files in a folder when many / large images are present. it also crashes the game in some cases when the tool is used. alternative libraries should be tested for this feature, even if multiple dependencies are required, although it does allow for text based raster formats which might be nice in the future.

**Comment by bobombolo** [comment]
the original library I used, imagesize: http://www.geoffrichards.co.uk/lua/imagesize/doc/ , might still be the best option for this one feature, but it would be nice to stick with luarocks packages, so we should test imlib2 again for the purposes of this feature only. in that case another option might be mime: https://luarocks.org/modules/luarocks/mimetypes

**Comment by Tank-ACiD** [comment]
I would err with simplicity's sake, let the mod user specify the files they
want to load, also let them specify what material (classification schema)
they want for biome cover, what values they have for water and roads etc.
This way it is highly customizeable without having to code a lot of
overhead.

The remote is nice, and it's neat to be able to in-game change values, but
I think we should fork the code, one to focus on using a config file or
values set in the init.lua and one with a fancy interface, bells and
whistles?

**Comment by bobombolo** [comment]
i think that the remote, which is really just editing a config file (realterrain.settings in the world folder) is essential to being able to display raster analysis results, time-series data, etc in an engaging way. messing around outside of the game would be too much work and wouldn't feel like you are using a piece of software, rather that you are hacking something, as you said early on. also the ability to validate form entries in -game is nice, since editing a config file by hand you could enter all kinds of garbage and get no feedback -- in game you can be told what fields are wrong and dropdown boxes eliminate garbage input altogether.

also the remote is optional. you could edit the settings file by hand and never touch the remote. no need to branch the code...

**Comment by bobombolo** [comment]
moved to #21
