### ISSUE TITLE
dropdowns for nodetypes and available schemas

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#24]
need to automate the field-heavy forms for biomes and soon to come roads, buildings, rivers, ores/soil layers and enable dropdowns whenever possible

may need to add node types

need to make biome, roadcover, etc tables more programmatic to allow adding new categories easier.

**Comment by Tank-ACiD** [comment]
where does one see a list of voxel values? ie.
content_id(default:<block_type>")

id like to start building arrays to be used in drop-down menus to allow the
user to select which type of block to be used in biome, water, road
rendering

**Comment by bobombolo** [comment]
yes there is a global table of registered nodes. i want to edit the minetest wiki to list this and other global tables. really nice would be a form that uses a graphical inventory-style drag and drop method for filling these values...

**Comment by Tank-ACiD** [comment]
yeah but where! i searched the github repository for the strings and didn't
find anything listing the values associated with the constant strings! lol
. Where is this table of registered node values you speak of! :)

**Comment by bobombolo** [comment]
one thing that is a hazard in minetest modding is that content ids change as mods load. for example if I do a minetest.get_content_id in the main portion of the mod, these will be invalid once all mods, including default game sub mods, load, so they will be different inside register_on_generate() callback which is why mapgen mods do their cids inside this callback...

**Comment by Tank-ACiD** [comment]
http://wiki.minetest.net/Blocks

has the blocks and graphics....now..what are the content ids :)

**Comment by Tank-ACiD** [comment]
oh i see itemstring listed..that's what we use?

**Comment by bobombolo** [comment]
yes cids are only for rapid use inside a voxelmanipulator instance

**Comment by bobombolo** [comment]
content ids are dynamic so that is also an issue with outputting useful rasters that contain only CIDs... it would be so easy if cids were permanent

**Comment by Tank-ACiD** [comment]
but the item string is permanent, right? We let then choose the item,
associate it with an item string, save that item string to the settings
file, and then the world will generate using those block types?

As much as i'd like to have a drop-down menu of "name [image]" I don't see
how that's going to be possible. I think the user will just have to refer
to the Wiki page to reference the graphics? I see the wiki is
incomplete..doesn't have the various wool colors, needs to be flushed
out/completed. Of course they can [;ay around..if they don't like a
coverage block type, then can change and regen th world! :)

**Comment by bobombolo** [comment]
i will deal with this. it IS possible, as any inventory mod will demonstrate. the names of the nodes are permanent and you can always get the cid with minetest.get_content_id(nodename) call, but cids themselves are dynamic. the wiki is CRAP. better to have it all in-game like an inventory mod does.

**Comment by bobombolo** [comment]
that way any mod that registers node types will also be available to the user

**Comment by Tank-ACiD** [comment]
right, but we need to develop an array of records {node type, plain text
name, image}. I can see where we should be able to get a list of node types
defined in the default game, possibly node types added from mods somehow?
but then we'll have to manually correlate plain text descriptors and images
to said node types ..which i feel realistically limits us to the default
game-defined types?

**Comment by Tank-ACiD** [comment]
https://forum.minetest.net/viewtopic.php?f=9&t=11294

we can use this to display all nodes, then go through and select all the
'completely square' nodes and then choose which ones we want the user to be
able to define as a road, water and biome value.

I didn't see a way within registered_node to actually tell if the node was
a complete voxel
http://dev.minetest.net/minetest.register_node

...I modded the code to display a subset of nodes where drawtype = normal
 (eliminate a lot of planar nodes) ..that looked to be only solid blocks.

we can then see the texture it uses, and maybe display that next to it? I
haven't looked at any inventory mod code, but maybe it's all there?

here you can see the blocks I think are candidates for realterrain menus...


for key,value in pairs(minetest.registered_nodes) do
if value.drawtype == "normal" then
print (key)
if value.tiles ~= nil then
print (dump{value.tiles})
end
end
end

**Comment by Tank-ACiD** [comment]
a little easier to read, and we can easily pull the 'top' png from this
code (value.tiles[1]).

for key,value in pairs(minetest.registered_nodes) do
if value.drawtype == "normal" then
print (key)
if value.tiles ~= nil then
for i,j in pairs(value.tiles) do
if (type(value.tiles[i]) == "table") then
print (dump(value.tiles[i]))
else
print ("-- "..value.tiles[i])
end
end
end
end
end

**Comment by bobombolo** [comment]
yes something like this or something using an inventory type screen will be ideal.

**Comment by bobombolo** [comment]
i will be refactoring the settings table so that it saves to a human readable text file (or more human readable) there are issues with exporting (serializing) tables within tables, so i may have to break the biome table to its own file, which might be nice anyway. i am planning to refactor the biome code to be more programmatic so that adding and removing biomes is easy and the code takes less lines of hard-coding

**Comment by bobombolo** [comment]
see #25

**Comment by bobombolo** [comment]
thanks for identifying a method that works in windows and writing the os detection https://github.com/Tank-ACiD/realterrain/blob/master/init.lua#L154-L186  I have incorporated it in the latest master.

**Comment by bobombolo** [comment]
image based selection has been added to the biomes form.

![screenshot_20151031_093508](https://cloud.githubusercontent.com/assets/12679496/10864655/bf992306-7fb2-11e5-80b8-236d0440f72b.png)

![screenshot_20151031_093550](https://cloud.githubusercontent.com/assets/12679496/10864657/c97ec2c2-7fb2-11e5-810f-85a5270102af.png)

the only complaint I have is that in order to pass values the "label" field must be used on the "item_image_button" formspec element, however, this label field is ALSO shown over the image, which is a little distracting and unnecessary since tooltips area already generated from the item description automatically. I'm not sure what to do about this, other than filing a bug report with minetest core...

**Comment by Tank-ACiD** [comment]
can we control the label font attributes like size (extremely small) or
color (alpha for invis) for now? Worst case, can we use/pass a number and
then implement a lookup table to get the proper string, more code/work but
reduces the text spam.

**Comment by bobombolo** [comment]
yes there are other ways to pass the value, like in the "name" field itself which can then be parsed out later, but the way it works now is just so simple and elegant I want to think about it for a while. i don't think there is a way to change the label font.

**Comment by bobombolo** [comment]
there are also no "hidden" form fields, which would work as well.

**Comment by bobombolo** [comment]
at any rate, this is a vast improvement in usability... have you tried it?

**Comment by bobombolo** [comment]
https://github.com/minetest/minetest/issues/3322 maybe it will be dealt with soon
