### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#25]
Suggestion to include a default settings file in the mod's main directory, this way, all default settings can be removed from the code, and the user can treat it as a 'master' or default setting file.

If no settings file is found in the worldpath in load_settings, copy the default one, then read it.

**Comment by bobombolo** [comment]
instead of setting defaults in the mod itself, i might create a more human readable settings file that is loaded as a default or edited in lieu of using the settings tool (remote)

**Comment by bobombolo** [comment]
and there is something to be said for defaults being in the mod itself since a minetest mod in a single self-contained file has its appeal

**Comment by bobombolo** [comment]
with everything working, I don't want to change this right now. all a user has to do is run the game once and use the remote tool, this will generate a settings file in the world folder which they can then edit by hand to their heart's content and their own risk.
