### ISSUE TITLE
automatic detection of bit depth

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#26]
rendering seems to have an issue with 16bit.  have a huge artifact in the middle of my landscape (using 16bit PNG)
![16bitartifact](https://cloud.githubusercontent.com/assets/5496265/10737977/125d2d2c-7be3-11e5-979f-26f29b250439.png)

**Comment by Tank-ACiD** [comment]
here is the 16bit tif, same spot, with only the surface rendered, I modified the code not to create nodes below the surface to try and speed up landscape generation...

![dem16tif](https://cloud.githubusercontent.com/assets/5496265/10739433/54914064-7bea-11e5-8257-af02080aea3a.png)

**Comment by bobombolo** [comment]
does it speed up generation? the code still has to iterate throughout each node in the mapchunk so i doubt it does much...

**Comment by bobombolo** [comment]
those artefacts are strange.

**Comment by bobombolo** [comment]
btw taking screenshots from within minetest is done by pressing F12 and is limited to the game screen
F1 disables the hud, F2 disables chat, and F5 toggles levels of debug info
these make for cleaner screenshots

**Comment by bobombolo** [comment]
and if it is night and you wanna change the time use /time 7000

**Comment by bobombolo** [comment]
your latest google drive dem appears 16 bit in photoshop, but if i use it in the mod it is only two heights. even if i render it as 8 bit it is only two heights. but if I contrast stretch it in photoshop it works fine. (not looking for the artefact yet). i have to look at the code a bit.

**Comment by Tank-ACiD** [comment]
I'm just generating/looking at them in ArcGIS. I can also get GRASS and see
if it confirms. I can also test load them in WorldPainter, which uses
standard java libraries, to ensure that they are legit 16bit.

**Comment by bobombolo** [comment]
this might also be a place to try to use standard python libraries to access image information (via lunatic) see #17

**Comment by bobombolo** [comment]
i switched the mod to use imlib2 temporarily and it also doesn't see these pixels (it can see 16 bit but treats it as 8 -- it sees zero and one). I think you have a raster that is storing pixels as 16 bit floats or something. like arc is setting the max and min elev in the GeoTiff tags (which we can't really read) and then is storing the actual value to a high level of accuracy in the pixels as a ratio of the max elev. photoshop is able to actually contrast-stretch this and then save as a typical raster with typical values. we may need to explore how to read geotiff tags more. "imagesize" spits out an error when the dem is first loaded, in fact, about "unknown tiff tags"
<pre>
TIFFReadDirectory: Warning, Unknown field with tag 33550 (0x830e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 33922 (0x8482) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 34735 (0x87af) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 34737 (0x87b1) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 42112 (0xa480) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
</pre>

I spent a few hours trying to get lunatic python to work today hoping to use grass to read geotiff headers or raw DEM files. I would rather not have to reinvent the wheel for reading geo raster information. however, if we cannot solve this file exporting issue we might have to get into the tiff tags...

**Comment by bobombolo** [comment]
a list of geotiff tag keys: http://www.remotesensing.org/geotiff/spec/geotiff2.7.html

the key id's don't seem to be the same as the ones spit out by imagesize above.

I can confirm that 16 bit files work, I have used the dem tiles downloaded from GeoBase which are 16 bit, but the pixels are storing integers not floats. they are also storing centimetres not metres so i have to scale the vertical to 100.  i could be wrong about that because the canadian DEMs are one meter vertical resolution so that could have to do with the dem not being interpreted properly. they are signed integer pixels afterall, so magick might be reading them incorrectly... 

 i also think the zero level is referenced from a tag when opened in a GIS so that is something we should be able to extract from geotiff tags, (or always use the vertical offset setting in the tool). the metadata for the dem tile I am using is:

Band 1
STATISTICS_MAXIMUM=3482
STATISTICS_MEAN=1901.8731397027
STATISTICS_MINIMUM=554
STATISTICS_STDDEV=539.34732475687
Dimensions
X: 9601 Y: 4801 Bands: 1
Origin
-118,52.0001
Pixel Size
0.000208333,-0.000208333
No Data Value
*NoDataValue not set* 
Data Type
Int16 - Sixteen bit signed integer 
Pyramid overviews
Layer Spatial Reference System
+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs
Layer Extent (layer original source projection)
-118.0001041666666737,50.9998958333333334 : -115.9998958333333405,52.0001041666666666
Band
Band 1
Band No
1
No Stats
No stats collected yet

**Comment by Tank-ACiD** [comment]
good points. I believe I have been outputting the 16bits as float, but do
have the option to select integer. I'll work on exporting a dem in every
format that ArcGIS will allow with "Copy Raster" and run them through
imagemagicks 'identify' tool and lua magick's imagesize.

Allergies have me crying today so it's hard to focus on a screen, took some
otc medicine...stupid Texas, tons of allergens in the air most of the year.
Will be putting some time into expanding the lit review concerning Virtual
Geographic Environment publications later today

**Comment by bobombolo** [comment]
I have confirmed in QGIS that the top left corner of the 16bit DEM I am using is exactly correct. I was wrong they are not cm they are m. So this is working it is just a file export issue.

**Comment by bobombolo** [comment]
those artefacts at the top of this issue look like they are attempts to generate the world that were aborted, some settings were changed and then the game was launched again and started to render properly. as I said elsewhere once the map is generated it is saved and so these artefacts will go away if you delete the map.sqlite file and play the game again. let me know if this is not the case.

**Comment by bobombolo** [comment]
what kind of information are you getting from IDENTIFY and imagesize? you mean within the mod itself? imagesize is actually a standalone lib if you are talking about the mod. are you able to get bit-depth from either of these methods? I am sure there must be a way to get the bit-depth from imagemagick but maybe there is no lua binding for the particular imagemagick function we need to run.

i have a cold and cannot really do more today either.

**Comment by Tank-ACiD** [comment]
the identify.exe program that comes with Imagemagick complete install gives
all sorts of info. You can see in my forked code I have it called using the
same methods we use to get the directory listing, with flags so that it
returns one line consisting of the image's bitsize. It takes a few seconds
to run on each of my rasters, but it works.

**Comment by bobombolo** [comment]
i think there is a way to do it within lua using something like:

<pre>
image.get_option(magick, key) 
</pre>
but I can't figure out the syntax

**Comment by bobombolo** [comment]
aha:
http://www.imagemagick.org/script/command-line-options.php#define

**Comment by bobombolo** [comment]
"quantum:format=type 	Set the type to floating-point to specify a floating-point format for raw files (e.g. GRAY:) or for MIFF and TIFF images in HDRI mode to preserve negative values. If -depth 16 is included, the result is a single precision floating point format. If -depth 32 is included, the result is double precision floating point format."

**Comment by bobombolo** [comment]
still, none of the options is an obvious way to get the bit depth so that sucks.

**Comment by bobombolo** [comment]
this is mostly an issue of the libraries we use. if we can get a lua wrapper for graphicsmagick it will be a non-issue see, #45
