### ISSUE TITLE
option to only generate surface

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#27]
add a config option to only generate surface nodes. To address gaps caused by nodes higher than 1 node above surrounding, we could go back through once world is set/wtitten and do a neighborhood analysis to see if the node is > in elevation than by more than 1 greater than neighbors and fill below by the difference.

This would be useful if people are doing purely 2D raster analysis. Might speed things up with way less notes to generate

In addition, add an option to generate a certain depth of soil below the surface, set by the user.

**Comment by bobombolo** [comment]
see original mention in #26

**Comment by bobombolo** [comment]
this is potentially one of the options for raster output #13

**Comment by Tank-ACiD** [comment]
yes, but I feel it shoudl also be an initia rendering option, helps speed
things up if one is not interested in anything below surface. it does
present an issue with water bodies using real water..so a minimum depth
value might also be good to incorporate, especially when we get to adding
strata interface (surface) dems for soil horizons and defining bedrock. In
my study area, bedrock is rarely deeper than 5 meters, so I would want to
limit the terrain generation to 5 meters since there is no interest for my
analysis below 5m (and might speed rendering up)

**Comment by bobombolo** [comment]
i still need to see some profiling comparissons to believe it actually speeds anything up, also i think this should be a raster output option, i have it in mind...

**Comment by bobombolo** [comment]
surface only water issues would be solved by a new node of water_static or something as discussed in #28

**Comment by Tank-ACiD** [comment]
I didn't see a water_static available in minetest, did I miss it?

**Comment by bobombolo** [comment]
no i was planning to add it. registering node types is the most rudimentary form of modding.

**Comment by bobombolo** [comment]
the only drawback is that the water wouldn't be animated. boooo hoooo

**Comment by Tank-ACiD** [comment]
well, the surface can be "animated" a sort of swirling, blobular motion?

**Comment by bobombolo** [comment]
I have written a function that accomplishes this, currently only for the raster output surface "slope" but it will be used by other raster outputs and any "surface only option" so for now this option only needs to be added to the settings form. however, this process adds processing time and may need to be refactored into a process that happens at the end of chunk generation (like how trees are added later) in a sort of "hole filling" process that is blind to the DEM.

![screenshot_20151030_191018](https://cloud.githubusercontent.com/assets/12679496/10861400/c99aa492-7f3a-11e5-858a-c962752e3ec2.png)

**Comment by bobombolo** [comment]
surface only is a mode in the game now but it does not in fact speed things up. see #36

**Comment by Tank-ACiD** [comment]
Understand on the speed issue, but it is a useful rendering option for
specific research applications. For instance, rendering subterranean
space(s) with a need for a viewable ground surface as a spatial reference
and/or performing nearest neighbor, Near, etc spatial operations. It would
be easier to cognitively grasp the magnitude of installing a well to a
natural resource if the soil was invisible. I can also think of under
ground cavern mapping/visualizations and underground natural watersystems,
along with manmade features. For archaeology, sometimes buildings or their
foundations are completely below the surface, we dig down, but in
reconstructing the landscape in minetest, it would be nice to 'see' the
surface as a reference point above the architecture to get a better sense
of soil deposition. What if the Sphinx gets covered up again? :)

**Comment by bobombolo** [comment]
you could still do this kind of thing, but there would be holes in the surface... and filling the surface could be added, but the performance will take a serious hit.
