### ISSUE TITLE
using water block as cover

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#28]
if we use real flowing water, will need to offset the water surface by -1, or somehow make it not spill when the terrain changes in a downslope situation, see screenshot.
![waterbleed](https://cloud.githubusercontent.com/assets/5496265/10745070/733f3454-7c0c-11e5-9c43-6a3cc0b57db6.png)

**Comment by bobombolo** [comment]
that has been done, slopes still cause spillover, will deal with this soon or register a non-flowing non-source water node

**Comment by bobombolo** [comment]
water is now static:

![screenshot_20151030_202302](https://cloud.githubusercontent.com/assets/12679496/10861614/172dfd90-7f44-11e5-8f33-5f6ad3b9e0e2.png)

**Comment by Tank-ACiD** [comment]
very nice,
