### ISSUE TITLE
option to handle off-raster blocks

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#29]
allow the user to decide how off-map area is handled. options are probably biome 1, air or some specific node like rainbow

**Comment by bobombolo** [comment]
instead of passing 0 off-raster results should return nil so that it can be handled differently, ie the biomes raster should pass nil not 0 because 0 is handled as biome1

**Comment by Tank-ACiD** [comment]
nil values will crash the mod. I have had 0 luck processing rasters with
nil values, hence why it's taken so long to generate non-nil rasters. I
think using 0 as lack of existing for any raster is good, allows for a
unified value to symbolize nil

**Comment by bobombolo** [comment]
i mean to pass nil from the get_pixel method in the mod, or some similar 
return like false

**Comment by bobombolo** [comment]
this could also be where we discuss the handling of the "nodata" value during export of rasters from a GIS. zero being a legitimate elevation. this could also eliminate the black/off-angle borders around dems, etc. and this might also have to do with reading GeoTiff tags...

**Comment by bobombolo** [comment]
off-raster values are now simply not rendered.
