### ISSUE TITLE
pure lua image libraries

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#3]
this is the main hang-up with this mod, recently imageloader mod added per-pixel PNG support to its BMP support:

https://github.com/kaeza/minetest-imageloader/tree/master/lib/pngLua

**Comment by bobombolo** [comment]
wrapping imagemagick's convert.exe like this guy did:

https://forums.adobe.com/message/6217975
<code>command = string.format('"start /D "%s\\bin" /B convert.exe "%s""', pluginPath, filePath)</code>

**Comment by bobombolo** [comment]
if we open to libraries then we have these options: http://lua-users.org/wiki/LibrariesAndBindings

**Comment by bobombolo** [comment]
I have PNGs ALMOST working in this dev branch: https://github.com/bobombolo/realterrain/tree/development
the problem is with https://github.com/bobombolo/realterrain/blob/development/pngLua/png.lua#L272-L276 where the entire image is read into an array. we would need to bypass the class constructors or modify them and modify the https://github.com/bobombolo/realterrain/blob/development/pngLua/png.lua#L280 function to access the pixels directly from the file rather than an array property. This should actually be pretty easy and would be my next approach, but I am going to work on libraries.

**Comment by bobombolo** [comment]
if we are open to os.execute (which like libraries requires insecure environment) we could use imagemagick: http://www.imagemagick.org/discourse-server/viewtopic.php?t=17079

**Comment by bobombolo** [comment]
need to figure out how to handle negative elevations, will image libraries choke on that?

**Comment by bobombolo** [comment]
minetest.request_insecure_environment()
https://forum.minetest.net/viewtopic.php?t=12471

an example of how to use this insecure environment is:
https://github.com/kaeza/minetest-irc/blob/master/init.lua#L4-L37

**Comment by bobombolo** [comment]
actually the best way to handle the pixel extraction is using a crop. 
<pre>
convert color.jpg -crop '1x1+48+48' -depth 16 txt:-
# ImageMagick pixel enumeration: 1,1,65535,srgb
0,0: (70.1961%,74.902%,79.6078%)  #B3B3BFBFCBCB  srgb(179,191,203)
</pre>

note, 16 bit values:
"The values are normally intergers. However as of IM v6.9.2-1, if the special define "-define txt:compliance=css" is given with "-depth 16" the values will be represented as percentage values with '%' signs. This is part of SVG, CSS compliance."

in order for all formats to produce the same output we will use this depth mode always

**Comment by bobombolo** [comment]
ah lua, ok so we need to capture the output from io.popen as per: 
http://stackoverflow.com/questions/132397/get-back-the-output-of-os-execute-in-lua
<pre>
function os.capture(cmd, raw)
  local f = assert(io.popen(cmd, 'r'))
  local s = assert(f:read('*a'))
  f:close()
  if raw then return s end
  s = string.gsub(s, '^%s+', '')
  s = string.gsub(s, '%s+$', '')
  s = string.gsub(s, '[\n\r]+', ' ')
  return s
end
</pre>

**Comment by bobombolo** [comment]
imagemagic calls from the commandline appears to be too slow

**Comment by bobombolo** [comment]
stashing the imagick efforts in https://github.com/bobombolo/realterrain/tree/imagick

moving on to imlib2 library

provides pixel level access via img:get_pixel(x, y): http://asbradbury.org/projects/lua-imlib2/doc/

**Comment by bobombolo** [comment]
help from rubenwardy re insecure environment
https://github.com/rubenwardy/minetest_web_panel/blob/master/mods/mwcp/http.lua#L22-L30

**Comment by bobombolo** [comment]
OK, luarocks and imlib2 working, successful test of 16 bit files
![screenshot_20151019_143803](https://cloud.githubusercontent.com/assets/12679496/10592184/486172a8-766f-11e5-9168-b97c7d07eac3.png)
this branch is at: https://github.com/bobombolo/realterrain/tree/imlib2
lua-imlib2 docs here: http://asbradbury.org/projects/lua-imlib2/doc/

**Comment by Tank-ACiD** [comment]
ok, so I see the vrange but the imlib2 docs only mention values in 8 bit
range..will look at branch soon :)
