### ISSUE TITLE
improve performance

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#32]
constant performance optimization needs to be a priority.  see #31 for a standard procedure to benchmark the impact of new features or optimizations. I had performance going really well but then I refactored the generation code (separated into various functions for readability and reusability) and now the results are much worse.

**Comment by bobombolo** [comment]
benchmark for the night of the 30th push called 'refactoring and other issues solved'
normal mode:
[DEM] 887 ms  mapchunk (0, 2, 0)
[DEM] 766 ms  mapchunk (0, 3, 0)
[DEM] 927 ms  mapchunk (1, 2, -1)
[DEM] 1387 ms  mapchunk (1, 2, 0)
[DEM] 949 ms  mapchunk (0, 2, -1)
[DEM] 979 ms  mapchunk (1, 3, -1)
[DEM] 830 ms  mapchunk (1, 3, 0)
[DEM] 1062 ms  mapchunk (0, 3, -1)

slope mode:
[DEM] 1138 ms  mapchunk (0, 2, 0)
[DEM] 1093 ms  mapchunk (0, 3, 0)
[DEM] 1348 ms  mapchunk (1, 2, -1)
[DEM] 1193 ms  mapchunk (1, 2, 0)
[DEM] 1365 ms  mapchunk (0, 2, -1)
[DEM] 1291 ms  mapchunk (1, 3, -1)
[DEM] 1099 ms  mapchunk (1, 3, 0)
[DEM] 1321 ms  mapchunk (0, 3, -1)

**Comment by bobombolo** [comment]
trying to recover performance after refactoring the mapgen code. normal mode is now at:

[DEM] 520 ms  mapchunk (0, 2, 0)
[DEM] 467 ms  mapchunk (0, 3, 0)
[DEM] 633 ms  mapchunk (1, 2, -1)
[DEM] 1139 ms  mapchunk (1, 2, 0)
[DEM] 549 ms  mapchunk (0, 2, -1)
[DEM] 640 ms  mapchunk (1, 3, -1)
[DEM] 499 ms  mapchunk (1, 3, 0)
[DEM] 664 ms  mapchunk (0, 3, -1)

seems like bundling varables into tables and then accessing them is very slow in lua, need to unpack as many as possible.

**Comment by bobombolo** [comment]
trying to improve and now i have crazy values:

[DEM] 1871 ms  mapchunk (0, 2, 0)
[DEM] 1938 ms  mapchunk (0, 3, 0)
[DEM] 184 ms  mapchunk (-1, 2, -1)
[DEM] 230 ms  mapchunk (-1, 2, 0)
[DEM] 4190 ms  mapchunk (0, 2, -1)
[DEM] 203 ms  mapchunk (-1, 3, -1)
[DEM] 249 ms  mapchunk (-1, 3, 0)
[DEM] 272 ms  mapchunk (-1, 2, 1)
[DEM] 8024 ms  mapchunk (1, 2, -1)
[DEM] 4528 ms  mapchunk (1, 2, 0)

**Comment by bobombolo** [comment]
wow it just gets worse:

[DEM] 2017 ms  mapchunk (0, 2, 0)
[DEM] 2042 ms  mapchunk (0, 3, 0)
[DEM] 7533 ms  mapchunk (1, 2, -1)
[DEM] 4569 ms  mapchunk (1, 2, 0)
[DEM] 353 ms  mapchunk (1, 2, 1)
[DEM] 326 ms  mapchunk (0, 2, 1)
[DEM] 3481 ms  mapchunk (1, 3, 0)
[DEM] 367 ms  mapchunk (1, 3, 1)
[DEM] 361 ms  mapchunk (0, 3, 1)
[DEM] 4974 ms  mapchunk (0, 2, -1)
[DEM] 8354 ms  mapchunk (1, 3, -1)
[DEM] 6366 ms  mapchunk (0, 3, -1)

**Comment by bobombolo** [comment]
slope is performing better than "normal" [DEM] 1084 ms  mapchunk (0, 2, 0)
[DEM] 1083 ms  mapchunk (0, 3, 0)
[DEM] 1309 ms  mapchunk (1, 2, -1)
[DEM] 1148 ms  mapchunk (1, 2, 0)
[DEM] 1393 ms  mapchunk (0, 2, -1)
[DEM] 1393 ms  mapchunk (1, 3, -1)
[DEM] 1155 ms  mapchunk (1, 3, 0)
[DEM] 1464 ms  mapchunk (0, 3, -1)
[DEM] 1079 ms  mapchunk (-1, 2, 0)
[DEM] 1060 ms  mapchunk (-1, 2, 1)
[DEM] 1175 ms  mapchunk (0, 2, 1)
[DEM] 1150 ms  mapchunk (-1, 3, 0)
[DEM] 1039 ms  mapchunk (-1, 3, 1)
[DEM] 1307 ms  mapchunk (0, 3, 1)
[DEM] 1439 ms  mapchunk (-1, 2, -1)
[DEM] 1402 ms  mapchunk (-1, 3, -1)

although it is clear that the "filling beneath" process is causing most of the processing time given that even AIR only chunks are taking a similar amount of time to generate

**Comment by Tank-ACiD** [comment]
interesting

**Comment by bobombolo** [comment]
i created a few display modes for "cover" which ignores underground, and "shell" which ignores everything but elevation and places a single node. even SHELL is getting horrible times.

I think this is all caused by trying to stash content id's and biome settings in tables. I am doing this to try to make future development of features that allow users to alter raster symbology and non-arbitrary numbers of biomes easier, but the downfall is that accessing table elements, especially multiple levels deep, is very slow. here are the results of the shell accessing a table of CIDs:

[DEM] 6034 ms  mapchunk (0, 2, -2)
[DEM] 4742 ms  mapchunk (0, 2, -1)
[DEM] 5588 ms  mapchunk (0, 2, -3)
[DEM] 8273 ms  mapchunk (3, 2, -3)
[DEM] 9333 ms  mapchunk (1, 3, -4)
[DEM] 9533 ms  mapchunk (2, 3, -4)
[DEM] 6574 ms  mapchunk (0, 3, -4)
[DEM] 5884 ms  mapchunk (0, 4, -3)
[DEM] 5323 ms  mapchunk (0, 4, -2)
[DEM] 8785 ms  mapchunk (1, 4, -3)
[DEM] 8565 ms  mapchunk (1, 4, -2)
[DEM] 9662 ms  mapchunk (1, 2, -4)
[DEM] 6420 ms  mapchunk (0, 2, -4)
[DEM] 6139 ms  mapchunk (0, 4, -4)

here is the same "shell mode" with a non-table CID reference: 

[DEM] 4880 ms  mapchunk (1, 3, -3)
[DEM] 5529 ms  mapchunk (2, 3, -3)
[DEM] 4957 ms  mapchunk (2, 3, -2)
[DEM] 6116 ms  mapchunk (1, 3, -2)
[DEM] 4957 ms  mapchunk (1, 2, -2)
[DEM] 6344 ms  mapchunk (1, 2, -3)
[DEM] 7047 ms  mapchunk (2, 2, -3)

but that doesn't account for the order of magnitude difference that i got after refactoring.

I modified the get_pixel function to only return elevation if that's all we need, which it often is. rerunning SHELL in that mode I got these results:

[DEM] 2259 ms  mapchunk (3, 2, -4)
[DEM] 2075 ms  mapchunk (3, 2, -3)
[DEM] 1925 ms  mapchunk (3, 2, -2)
[DEM] 1729 ms  mapchunk (2, 1, -3)
[DEM] 1627 ms  mapchunk (2, 1, -2)
[DEM] 2774 ms  mapchunk (3, 1, -2)
[DEM] 2463 ms  mapchunk (2, 1, -4)
[DEM] 3071 ms  mapchunk (1, 2, -4)
[DEM] 2869 ms  mapchunk (1, 1, -4)
[DEM] 2594 ms  mapchunk (1, 3, -4)
[DEM] 3063 ms  mapchunk (1, 1, -3)
[DEM] 2455 ms  mapchunk (1, 1, -2)
[DEM] 2252 ms  mapchunk (3, 1, -3)

**Comment by bobombolo** [comment]
getting elevation only for slope mode now yeilds:

[DEM] 1225 ms  mapchunk (3, 2, -2)
[DEM] 1238 ms  mapchunk (3, 1, -3)
[DEM] 1245 ms  mapchunk (3, 1, -2)
[DEM] 1200 ms  mapchunk (2, 2, -2)
[DEM] 1200 ms  mapchunk (2, 1, -2)
[DEM] 1653 ms  mapchunk (2, 1, -3)
[DEM] 1337 ms  mapchunk (2, 2, -3)
[DEM] 1511 ms  mapchunk (2, 1, -4)
[DEM] 1539 ms  mapchunk (1, 2, -1)
[DEM] 1486 ms  mapchunk (2, 2, -1)
[DEM] 1490 ms  mapchunk (1, 1, -1)
[DEM] 1338 ms  mapchunk (2, 1, -1)

**Comment by bobombolo** [comment]
anyway a rollback is going to be needed. just tested this commit again: https://github.com/bobombolo/realterrain/blob/79e48db76ad673cf94cfb52cb3509ba7355d5c3f/init.lua

and here are the much faster results for fully generated map!

[DEM] 480 ms  mapchunk (3, 2, -3)
[DEM] 905 ms  mapchunk (3, 2, -2)
[DEM] 977 ms  mapchunk (3, 1, -3)
[DEM] 673 ms  mapchunk (3, 1, -2)
[DEM] 932 ms  mapchunk (2, 2, -2)
[DEM] 366 ms  mapchunk (2, 1, -2)
[DEM] 696 ms  mapchunk (2, 1, -3)
[DEM] 894 ms  mapchunk (2, 2, -3)
[DEM] 490 ms  mapchunk (2, 1, -4)
[DEM] 410 ms  mapchunk (1, 2, -3)
[DEM] 400 ms  mapchunk (1, 2, -2)
[DEM] 422 ms  mapchunk (1, 2, -1)
[DEM] 1279 ms  mapchunk (2, 2, -1)
[DEM] 430 ms  mapchunk (1, 1, -1)
[DEM] 440 ms  mapchunk (2, 1, -1)

**Comment by bobombolo** [comment]
http://www.lua.org/gems/sample.pdf

**Comment by bobombolo** [comment]
it is very difficult to do any profiling on the inner workings of the magen logic because the times are much less than a millisecond so even aggregating them really just gives you one millisecond per iteration so around 500,000 (80x80x80) milliseconds which is garbage. So I am not sure where the time is going... even routines that should be dead simple like the "shell" mode are taking several seconds to generate a chunk

**Comment by bobombolo** [comment]
rolled back somewhat:

SLOPE:
[DEM] 320 ms  mapchunk (0, 2, 0)
[DEM] 269 ms  mapchunk (0, 3, 0)
[DEM] 407 ms  mapchunk (1, 2, -1)
[DEM] 363 ms  mapchunk (1, 2, 0)
[DEM] 421 ms  mapchunk (0, 2, -1)
[DEM] 495 ms  mapchunk (1, 3, -1)
[DEM] 320 ms  mapchunk (1, 3, 0)
[DEM] 476 ms  mapchunk (0, 3, -1)

ASPECT:
[DEM] 337 ms  mapchunk (0, 2, 0)
[DEM] 281 ms  mapchunk (0, 3, 0)
[DEM] 419 ms  mapchunk (1, 2, -1)
[DEM] 385 ms  mapchunk (1, 2, 0)
[DEM] 453 ms  mapchunk (0, 2, -1)
[DEM] 510 ms  mapchunk (1, 3, -1)
[DEM] 404 ms  mapchunk (1, 3, 0)
[DEM] 468 ms  mapchunk (0, 3, -1)

NORMAL:
[DEM] 602 ms  mapchunk (0, 2, 0)
[DEM] 288 ms  mapchunk (0, 3, 0)
[DEM] 349 ms  mapchunk (1, 2, -1)
[DEM] 722 ms  mapchunk (1, 2, 0)
[DEM] 348 ms  mapchunk (0, 2, -1)
[DEM] 445 ms  mapchunk (1, 3, -1)
[DEM] 377 ms  mapchunk (1, 3, 0)
[DEM] 436 ms  mapchunk (0, 3, -1)

this is for the latest commit: https://github.com/bobombolo/realterrain/blob/fbc63403ab03baf8335c13dcdb7694b3a57274ae/init.lua

**Comment by Tank-ACiD** [comment]
well as I understand and have seen, even with the 'settings' in the
minetest.conf, it only uses 1 core... or is it using GPU? What cpu
frequency are you testing at? I may have missed that info, not reading back
far enough into the issue.

**Comment by bobombolo** [comment]
i don't think these profiles have anything to do with the GPU as they are just the time lua takes to fill the values of a mapchunk using our logic, no rendering is done at this point, just generation and saving to sqlite and sending a signal to the client to update.

anyway incidental to some other work I compared imlib2 and magick's performance. they are similar:

IMLIB2:
[DEM] 431 ms  mapchunk (0, 2, 0)
[DEM] 243 ms  mapchunk (0, 3, 0)
[DEM] 830 ms  mapchunk (1, 2, -1)
[DEM] 570 ms  mapchunk (1, 2, 0)
[DEM] 315 ms  mapchunk (0, 2, -1)
[DEM] 433 ms  mapchunk (1, 3, -1)
[DEM] 379 ms  mapchunk (1, 3, 0)
[DEM] 381 ms  mapchunk (0, 3, -1)


MAGICK:
[DEM] 382 ms  mapchunk (0, 2, 0)
[DEM] 280 ms  mapchunk (0, 3, 0)
[DEM] 883 ms  mapchunk (1, 2, -1)
[DEM] 692 ms  mapchunk (1, 2, 0)
[DEM] 302 ms  mapchunk (0, 2, -1)
[DEM] 390 ms  mapchunk (1, 3, -1)
[DEM] 379 ms  mapchunk (1, 3, 0)
[DEM] 406 ms  mapchunk (0, 3, -1)
[DEM] 299 ms  mapchunk (-1, 2, -1)

**Comment by bobombolo** [comment]
#17 using python to access the pixels (Python Imaging Library) returns these results with a 16-bit dem ("mv") starting in 0,387,0 facing southeast clean map:

[DEM] 6568 ms  mapchunk (0, 5, 0)
[DEM] 279 ms  mapchunk (0, 4, 0)
[DEM] 1702 ms  mapchunk (1, 5, -1)
[DEM] 682 ms  mapchunk (1, 5, 0)
[DEM] 1056 ms  mapchunk (0, 5, -1)
[DEM] 600 ms  mapchunk (1, 4, -1)
[DEM] 402 ms  mapchunk (1, 4, 0)
[DEM] 497 ms  mapchunk (0, 4, -1)
[DEM] 264 ms  mapchunk (1, 4, 1)
[DEM] 255 ms  mapchunk (1, 5, 1)
[DEM] 279 ms  mapchunk (0, 4, 1)
[DEM] 308 ms  mapchunk (0, 5, 1)
[DEM] 253 ms  mapchunk (-1, 5, -1)
[DEM] 279 ms  mapchunk (-1, 4, -1)
[DEM] 258 ms  mapchunk (-1, 5, 0)
[DEM] 294 ms  mapchunk (-1, 4, 0)

using magick in 16-bit mode:

[DEM] 462 ms  mapchunk (1, 6, -1)
[DEM] 366 ms  mapchunk (1, 6, 0)
[DEM] 359 ms  mapchunk (0, 6, -1)
[DEM] 237 ms  mapchunk (-1, 6, -1)
[DEM] 250 ms  mapchunk (1, 6, 1)
[DEM] 204 ms  mapchunk (-1, 5, 1)
[DEM] 297 ms  mapchunk (-1, 4, 1)
[DEM] 238 ms  mapchunk (-1, 6, 0)
[DEM] 342 ms  mapchunk (0, 6, 0)

**Comment by bobombolo** [comment]
using python to access both the dem and the biome file is even slower: 

[DEM] 1645 ms  mapchunk (9, 4, -1)
[DEM] 1486 ms  mapchunk (9, 5, -1)
[DEM] 1046 ms  mapchunk (9, 4, 0)
[DEM] 897 ms  mapchunk (9, 5, 0)
[DEM] 2054 ms  mapchunk (10, 4, -2)
[DEM] 2346 ms  mapchunk (11, 4, -2)
[DEM] 2195 ms  mapchunk (9, 5, -2)
[DEM] 318 ms  mapchunk (9, 5, 1)
[DEM] 311 ms  mapchunk (9, 4, 1)
[DEM] 320 ms  mapchunk (10, 4, 1)
[DEM] 1344 ms  mapchunk (9, 4, -2)
[DEM] 1281 ms  mapchunk (10, 5, -2)
[DEM] 2173 ms  mapchunk (9, 5, -3)
[DEM] 2167 ms  mapchunk (10, 4, -3)
[DEM] 3183 ms  mapchunk (8, 5, -2)
[DEM] 2218 ms  mapchunk (8, 5, -1)
[DEM] 2453 ms  mapchunk (8, 5, -3)
[DEM] 2374 ms  mapchunk (7, 5, -2)
[DEM] 1925 ms  mapchunk (7, 5, -1)
[DEM] 3104 ms  mapchunk (7, 5, -3)

**Comment by bobombolo** [comment]
loading pixels in groups using commandline imagemagick or graphicsmagic (cropping to txt format and then parsing the output from stdout) was slower than making calls to python using lunatic-python. it is hard to beat a lua library that opens a file and keeps it open for all pixel calls. the overhead of opening the file for each 80x80 crop and then parsing the text output is too slow.

however during those experiments (see issue #45 ) some ideas revealed themselves about optimization, those are that it might be desirable to have a way to know a heightmap's maximum elevation so that Skyblocks don't even bother looping through all values. also off-raster blocks might totally bypass even building the heightmap and just exit from the on_generate loop.

for extremely deep chunks, like more than two chunks below the surface, it might be good to simply cache a mapchunk average elevation instead of being precise to the x,z elevation miles above it...

in general it seems like a waste to build a heightmap for each chunk that is in a vertical column above and below the 80x80 pixel "footprint" of the dem/cover file. it would be nice to cache these but so far I have found no better way than to treat the rasters as the cache. there is no "surface" value stored in the map.sqlite. even in other mods finding the surface in mapgen mods has meant scanning a column until dirt is found. (see gis mod). the only way non-mapgen maps store "surface" is by virtue of the surface being computable quickly with the perlin noise algorithm.

**Comment by bobombolo** [comment]
i have started investigations towards an approach that does not even use the on_generated() callback but instead just starts rendering the surface around the player, ignoring all skychunks and continues forceloading surface further into the distance. 

meanwhile the results of the "80x80 pixel enumeration CLI" experiments are yeilding chunk times of ten times what the current method uses. for now we are married to MAGICK. here is a screenshot that reveals I still have major map/pixel alignment issues in this experiment, but the generation times do not warrant further improvements:

![screenshot_20151121_185920](https://cloud.githubusercontent.com/assets/12679496/11321865/40fbd150-9084-11e5-8e2e-dd2385eab81f.png)

**Comment by Tank-ACiD** [comment]
right, it's always faster with generated, fake landscapes. this is the holy
grail when dealing with real data. Getting elevation range is easy enough
but does take scanning the entire file to build the descriptive statistics,
unless it's an ESRI generated DEM which I'm fairly sure stores statistics
in a separate file, because you can generate them if they don't and it
saves to a file.

**Comment by bobombolo** [comment]
my idea with the entire new generation method is to cache which dem pixels have already been mapped to the map. then they won't be revisited. my only uncertainty is how to trigger generation when the player moves around. i'm fairly certain that this approach will be radically faster and also give us better render distances. (ie, the generating will never stop and the LuaVoxelManipulator will forceload them) it could be as simple as on_tick() callback which is how my automata mod works: on_tick check player position, check raster cache, spiral out from position skipping already loaded surface to continue generating. if the relief is low this could render so fast that it blows our socks off. if you think about it a flat surface could be processed in an order of magnitude of time faster than a cube, which is what the mapgen does. so instead of processing 80x80x80 voxels of which only 80x80 will be surface, we could process 715x715 of flat surface in almost the same time.

**Comment by bobombolo** [comment]
and we could launch a lua library for interfacing with sqlite in order to cache the "surface" and other layers to a db as needed and that can be the final word on "surface"
http://luarocks.org/modules/luarocks/luasql-sqlite

**Comment by Tank-ACiD** [comment]
yes, sounding plausible and good!

**Comment by bobombolo** [comment]
even a simple text file listing extents of already-rendered surface area would work. one that erases sub-sumed rectangles when they are. this could even use a simple raster addition system...

**Comment by bobombolo** [comment]
the idea being to allow users to edit the world without it being constantly regenerated as they move or whatnot. also not ever wasting time regenerating anything.

**Comment by bobombolo** [comment]
it might be worth prooving the concept of loading chunks of dem raster using python image library to load crops of the dem as an array, though lunatic makes this costly as each returned value is a userdata value that has to be converted to string then number. still, might be better than CLI IM or GM

**Comment by bobombolo** [comment]
some things i ask my system to do just require unplugging and a hard boot.

**Comment by Tank-ACiD** [comment]
lol

**Comment by bobombolo** [comment]
I have added the performance enhancements relating to off-raster, sky and sub-surface min/max elevation caching have been pushed to master. they do speed things up quite a bit. they do not persist to a file, which could be done, but still, for the duration of a player's session they greatly reduce unnecessary reading of the rasters and generation decision loops.

**Comment by bobombolo** [comment]
some sample profiling for Slope mode:

[GEN] 473 ms  mapchunk (9, 1, -8)
[GEN] 408 ms  mapchunk (6, 1, -8)
[GEN] 997 ms  mapchunk (6, 1, -7)
[SUB] 1 ms  mapchunk (6, 0, -8)
[GEN] 419 ms  mapchunk (5, 0, -8)
[GEN] 411 ms  mapchunk (5, 1, -8)
[GEN] 611 ms  mapchunk (5, 2, -7)
[SKY] 1 ms  mapchunk (5, 2, -6)
[GEN] 477 ms  mapchunk (4, 0, -8)
[SUB] 1 ms  mapchunk (4, 1, -8)
[GEN] 806 ms  mapchunk (3, 1, -7)
[GEN] 724 ms  mapchunk (4, 2, -7)
[GEN] 546 ms  mapchunk (4, 2, -6)
[GEN] 470 ms  mapchunk (4, 2, -8)
[GEN] 301 ms  mapchunk (3, 2, -8)
[GEN] 709 ms  mapchunk (3, 2, -7)
[GEN] 620 ms  mapchunk (3, 2, -6)
[SUB] 1 ms  mapchunk (3, 0, -7)
[GEN] 543 ms  mapchunk (2, 1, -7)
[SUB] 1 ms  mapchunk (2, 0, -7)
[GEN] 346 ms  mapchunk (2, 1, -8)
[GEN] 722 ms  mapchunk (2, 2, -6)
[GEN] 657 ms  mapchunk (2, 2, -5)
[GEN] 554 ms  mapchunk (3, 2, -5)
[GEN] 822 ms  mapchunk (1, 1, -4)
[SUB] 1 ms  mapchunk (1, 0, -4)
[SUB] 1 ms  mapchunk (2, -1, -6)
[SUB] 1 ms  mapchunk (2, -1, -5)
[SUB] 1 ms  mapchunk (1, -1, -6)
[SUB] 1 ms  mapchunk (1, -1, -5)
[SUB] 1 ms  mapchunk (4, -1, -6)
[SUB] 1 ms  mapchunk (6, -1, -7)
[SUB] 1 ms  mapchunk (6, -1, -6)

**Comment by bobombolo** [comment]
initial tests bypassing the mapgen object are not good. I tried pregenerating the entire map at load time (the mandelbrot map) which went pretty fast, ie:
[GEN] 175 ms  mapchunk (0, 0, -1)
[GEN] 169 ms  mapchunk (1, 0, -1)
[GEN] 171 ms  mapchunk (2, 0, -1)
[GEN] 174 ms  mapchunk (3, 0, -1)
[GEN] 175 ms  mapchunk (4, 0, -1)
[GEN] 173 ms  mapchunk (5, 0, -1)

however there are major issues with the lighting. the screen capture shows (an albeit deformed result -- I have alignment issues again) that there is also no gain in terms of render distance. you still have to explore the map to load it, even though it has been generated... the failure to update the lighting is why you must use the mapgen object version of the voxelmanipulator rather than the regular vm. see: https://github.com/Splizard/minetest-mod-snow/issues/14

![screenshot_20151122_122001](https://cloud.githubusercontent.com/assets/12679496/11326195/bad5b110-9117-11e5-94b6-f8be26b49862.png)

**Comment by bobombolo** [comment]
so that might be a dead end. 

anyway here is a cool screenshot of the underside of the mandelbrot slope map made with the newly improved efficiency from this morning.

![screenshot_20151122_095404](https://cloud.githubusercontent.com/assets/12679496/11326202/1f2a814a-9118-11e5-9f87-4bb8f12e4f4c.png)

**Comment by bobombolo** [comment]
because I think it makes sense to do it anyway, for reasons of making manageable crops of large rasters or raster outputs, I want to compare the performance of pixel access from the entire raster compared with small crops, particularly of images that are not stored as files, using IM/GM img:crop() function and possibly taking it further to use the img:get_blob() function. breaking the blob into a heightmap array rather than reading from the image pixel by pixel, however, this may not gain anything at all, but it would be a good exercise. it also makes sense for scaling, which should be done more gracefully, especially scaling upwards, so that an enlargement would result in creating a scaled crop and perhaps applying a blur or dither.  even with a vertical scale then it might be nice to do a blur so that the step sizes are not so jagged.
thinking about doing raster analysis on crops is tricky though... like proximity, how can you do proximity on a crop of the entire raster, it would only be done inside the small extent of the crop... i guess there could still be a major benefit if the crop was as large as the proximity algorithm's max distance plus half the block width, then the results could be cropped back down to the block size. there would still be a benefit compared to trying to calculate proximity internally which is a horror story. of course an improved proximity algorithm could be ported to lua and might work well if we had one. speaking of which the distance algorithm currently used is so horrible I'm sure I can improve it somewhat. #46

**Comment by bobombolo** [comment]
getting blobs into tables of bytes/pixels is the challenge similiar to the challenge I had with writing the original mod with in-mod image pixel-access: http://forum.renoise.com/index.php/topic/44592-snippet-load-file-in-binary-to-lua-table-1-byte-per-entry-string/

**Comment by bobombolo** [comment]
might reopen this later
