### ISSUE TITLE
biome settings need to be table-ified

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#34]
in order to facilitate issue #33 we need to automate the biome settings. 

perhaps the biome file should be read first, then all values in the image should be the values that need to be filled out in the biome settings editor. these biome files could then be stored with the biome raster rather than in the world folder. this means that one biome file will not be useful (necessarily) with other biome images that have different values, but not necessarily.

**Comment by bobombolo** [comment]
wondering if the pixel value should be a setting. that way the painting of biomes could be easier, where biome 1 could be assigned to be 54 and biome 2 could be 125 etc. this way importing USGS landcover files would be easy still

**Comment by bobombolo** [comment]
the number of biomes could itself be a setting. the only difficulty is the defaults... if any

**Comment by Tank-ACiD** [comment]
right, if the total # is settable, the assignment variables for each biome
would then also have to be dynamic. We could do like ESRI and read in the
number of unique values (up to a max of course based on limited menu space)
and build the menu based on the unique values.

**Comment by bobombolo** [comment]
i think that is the way to go. i will do that very soon, if you can provide a USGS lc/lu raster i can play with it?

**Comment by Tank-ACiD** [comment]
same size as my other rasters, or?

**Comment by bobombolo** [comment]
getting unique-values is easy from using imagemagick's command line interface. the lua wrapper is missing things like histogram and enumerating pixels... bummer

**Comment by bobombolo** [comment]
no longer necessary since #37
