### ISSUE TITLE
biomes using USGS classes

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#37]
i have always wanted to add a feature that allows player to simply check a box so that the biome is determined by a random factor plus consideration of the slope, aspect, distance to water, altitude and latitude. rivers and roads could also be determined by curvature somehow, but mostly the biomes.

**Comment by Tank-ACiD** [comment]
May need to be more than 8 bit...It uses a three tier system, [1, [11,
[111, 112..]..]..]
While I don't see any defined 3rd tier for anything other than 1, I'm sure
it's possible as it is suggested in the literature users may break down a
2nd tier w/ multiple components into their unique component listed solely
as a 3rd tier.

The UK system looks to be only 2 tier, but I didn't dig into the literature
to see if they also recommend a creation of a third tier...

**Comment by Tank-ACiD** [comment]
lulc.tif shared via google drive
8bit unsigned

**Comment by bobombolo** [comment]
lulc.tif seems to work out of the box.
also on my system the selection of layer files handles subfolders just fine!

**Comment by bobombolo** [comment]
do you have a definitive list of the meanings of the various USGS LC/LU indexes used in the file you provided? i can't find a good list

**Comment by Tank-ACiD** [comment]
attached

**Comment by bobombolo** [comment]
i can't see an attachment can you link to it here?

**Comment by Tank-ACiD** [comment]
*land*cover.usgs.gov/pdf/*anderson*.pdf

**Comment by bobombolo** [comment]
http://landcover.usgs.gov/pdf/anderson.pdf

from that I get:

TABLE 2. Land use and land cover classification system for use with remote sensor data 
Level I
Level II
1 Urban or Built-up Land
11 Residential
12 Commercial and Services
13 Industrial
14 Transportation, Communications, and Utilities
15 Industrial and Commercial Complexes
16 Mixed Urban or Built-up Land
17 Other Urban or Built-up Land
2 Agricultural Land
21 Cropland and Pasture
22 Orchards, Groves, Vineyards, Nurseries, and Ornamental Horticultural 
Areas
23 Confined Feeding Operations
24 Other Agricultural Land
3 Rangeland 
31 Herbaceous Rangeland
32 Shrub and Brush Rangeland
33 Mixed Rangeland
4 Forest Land 
41 Deciduous Forest Land
42 Evergreen Forest Land
43 Mixed Forest Land
5 Water 
51 Streams and Canals
52 Lakes
53 Reservoirs
54 Bays and Estuaries
6 Wetland 
61 Forested Wetland
62 Nonforested Wetland
7 Barren Land 
71 Dry Salt Flats.
72 Beaches
73 Sandy Areas other than Beaches
74 Bare Exposed Rock
75 Strip Mines Quarries, and Gravel Pits
76 Transitional Areas
77 Mixed Barren Land
8 Tundra 
81 Shrub and Brush Tundra
82 Herbaceous Tundra
83 Bare Ground Tundra
84 Wet Tundra
85 Mixed Tundra
9 Perennial Snow or Ice
91 Perennial Snowfields
92 Glaciers

TABLE 3. Standard land use code first level categories * 
1. Residential
2. Manufacturing (9 second level categories included)
3. Manufacturing (6 second level categories included)
4. Transportation, communication, and utilities
5. Trade
6. Services
7. Cultural, entertainment, and recreation
8. Resource production and extraction
9. Undeveloped land and water areas

Level 1
Level II
Level III
1. Urban or built-up
   11. Residential   
111. Single-family Units
112. Multi-family Units
113. Group Quarters
114. Residential Hotels
115. Mobile Home Parks
116. Transient Lodging
117. Other

Level II 
Level III 
21. Cropland and Pasture 
211. Cropland 
212. Pasture

TABLE 4. U.S.G.S. Level 1 Land Use Color Code 
1. Urban or Built-up Land
Red (Munsell 5R 6/12)
2. Agricultural Land 
Light Brown (Munsell 5YR 7/4) 
3. Rangeland 
Light Orange (Munsell 10YR 9/4) 
4. Forest Land 
Green (Munsell 10GY 8/5) 
5. Water 
Dark Blue (Munsell 10B 7/7) 
6. Wetland 
Light Blue (Munsell 7.5B 8.5/3) 
7. Barren Land 
Gray (Munsell N 8/0) 
8. Tundra 
Green-Gray (Munsell 10G 8.5/1.5) 
9. Perennial Snow or Ice 
White (Munsell N 10/0)

**Comment by bobombolo** [comment]
I think it might be sufficient to use the first tier only. that is only biomes 1-9. who is going to set trees and shrubs for all the sub-tiers? maybe...i have to think about this. also category 5 makes water layer redundant and the category 1 makes roads layer redundant...

**Comment by Tank-ACiD** [comment]
yes thats the foundation, people can expand it thought i'm afraid, causing
a potential value of 311, 312 etc , values > 256. maybe we can choose to
just not support tier III

**Comment by Tank-ACiD** [comment]
I would think a majority of people, rendering real-world landscapes, will
be using this type of single raster to define what's a road, water,
farmland etc. However, probably as often, people willl have seperate raster
datasets of roads and rivers...I'm not very opinionated on providing
support for both methods at the moment, down the road, maybe we can add
support for a Master Raster and let them choose USGS, British
classification, australian, etc.

**Comment by Tank-ACiD** [comment]
...and the most important, Canadian, of course... as that's the whole
reason we have GIS! :)

**Comment by bobombolo** [comment]
ya. tier two and especially three is too fine. it would be handy if my mod was to start automatically spawning buildings, then it could define the types of buildings, etc...
however, I might set all the defaults in the mod to handle values of 1 or 10-19 as biome1 (concrete) and 2 or 21-29 as Ag, etc. and disallow the setting of pixel values... it's too complicated. we could spend a half a year converting the long descriptions of the different categories into minetest node types and probabilities... even including multiple tree types per biome...

anyway if we decide to go to tier 3 it is no thing to handle 16bit lu/lc files...

**Comment by bobombolo** [comment]
hm, yeah maybe if the rivers layer is present we can ignore the Landcover category for water, and if there is roads, we can ignore the urban category. however, providing the extra layer files may not even add any benefit since the max resolution will always be the dem resolution... and if it is not then we have a whole new level of refactoring to provide different levels of detail. frankly I think that all these questions of scale and varying resolution should be tackled by handling everything through GDAL calls, and even use real coordinates. in that sense the only settings would be the setting of the origin coordinates and the voxel x,y,z scales... the only other benefit i can see for river and roads files is that you can have water crossing roads and such.

BUT for now if we are going to use landcover maybe we should abandon the other layer files.

**Comment by bobombolo** [comment]
also anyone who has the means to get or create a rivers layer, roads layer and a biome layer has the means to merge these into a single landcover layer...

**Comment by bobombolo** [comment]
generating a list of unique values via looking at each pixel in the biome layer is very slow on large files... not sure if it is an option. might be more practical to refactor to assume the use of USGS classifications...

**Comment by bobombolo** [comment]
making calls to IDENTIFY and CONVERT would be nice for things like getting bit depth and pixel enumeration but it is another place where cross-platform issues may arise. still it might be worth it in spite of it slowing load times down considerably...

**Comment by bobombolo** [comment]
in fact the mod might just have a setting at the top of the init file called OS and that can be win or nix and then we can set all our filesystem and IMagick command names based on that...

**Comment by Tank-ACiD** [comment]
using one raster would free up some processing (albeit slightly) and disk
space. I suppose it would be a matter of which is easier to develop and
maintain? This is more of a remote-sensing issue, what format is someone
more likely to be able to access and download and how can we facilitate the
rendering of the landscape with the least possible amount of work on their
end.

**Comment by bobombolo** [comment]
well as for that, i think that the mod should simply use data available online datasets and that would be DEMS and USGS LC/LU files and most of them are going to be tiled to the same extents. the default biome settings should be tuned to reflect the LC/LU codes and then the user can tune them as wanted. that way later we can add level 2 refinement for those with a form for each tier 1 category. this also still respects users who wanna use this as a "worldpainter"mod not just the GIS users. they can go into the biome editor and change the defaults to their own use, but the decimal system for 10 tier one categories makes it easy for them to paint biomes, roads and water in photoshop the way the mod was originally designed with breakpoints every 10 pixel values...

it might not be a trivial issue to only open a single landcover file since these recent issues i've had with crashing my whole system only occur when I have all 4 files for your study area open. frankly if the presence of information in the three cover layers is mutually exclusive, why have them?

**Comment by Tank-ACiD** [comment]
true and true.

**Comment by bobombolo** [comment]
it certainly is more attainable today than writing a system that can handle an arbitrary number of biomes and saving to a separate config file...

**Comment by bobombolo** [comment]
hm I just refactored to use the USGS codes, but your lc/lu file has areas marked as "5" which are obviously not water. is your file a standard USGS coded file?

**Comment by Tank-ACiD** [comment]
no, i just made up numbers and assigned then based on a reclassification of
elevation.
I don't have USGS lulc values since my area is in Mexico :) What I could do
is perform a lulc classification, will take me a good while to perform
spectral analysis (I do have rgb image to perform it, it's just a lengthy
process and one I did like 5 years ago, so I'm rusty)

**Comment by bobombolo** [comment]
oh i see. it did look like a reclass of elevation...

**Comment by bobombolo** [comment]
pushed a new branch called USGS to git: https://github.com/bobombolo/realterrain/tree/usgs

if this is the way we want to go with cover files then we should continue on this branch. the way this works is that if a pixel is classed as either tier one two or three it is collapsed to the tier one and  biomes 1-9 are assigned as per usual. water is just another biome (5) as are roads/urban (1).

**Comment by bobombolo** [comment]
instead of doing a reclass of landsat you could just reclass your landcover file to not include any urban or water classes, and then overlay your water and roads layers as such, see what kind of result that gives.
this build feels cleaner and faster but that is subjective.
anyway i like it. what i don't like is my old version of photoshop which is not assigning correct pixel values... and it does too much antialiasing.

**Comment by bobombolo** [comment]
i might never be happy with biomes until they are more fuzzy. it would be nice to have a primary and secondary landcover, primary and secondary shrub, and a primary and secondary tree, with probabilities for all so that the land is a little more mottled and so there are more options. especially for say, wetlands, which should have a probability for being water node every once in a while.
or to simplify this, each biome could have a probability of being another biome. so that every once in a while the wetlands biome is the water biome, and the cropland biome is the rangeland biome. the fuziness of the actual biome boundaries can be handled by the image itself, not too worried about that.

**Comment by Tank-ACiD** [comment]
My money is on people having non-fuzzy demarcation biome rasters. With GIS
using the topological model to store data, borders, nodes etc are ideally
shared. My suggestion would be to add a checkbox option for "Fuzzy
Boundaries" and include a fuzzyness value. That way if people want mottled
biomes it will do it (excluding urban/roads and waterways of course), sort
of like how minecraft does it now, but if they need sharp delineations like
what is grazeable land (property boundary) and not, it will render the
real-world exactly at it's remotely sensed, providing accurate analysis,
still allowing someone who wants a more visually pleasing environment for
immersion to get fuzzy boundaries.

**Comment by Tank-ACiD** [comment]
In addition, the water lulc, I strongly suggest having the option to render it one unit below the actual DEM surface. Ideally the DEM should reflect a river's lower level, but unless you are using LIDAR data at 1-2m horizontal resolution and 1mm height, most all remote sensed data's water nodes will be flush with the surface. it just looks better to me when dealing with low-res landscapes. :)

**Comment by bobombolo** [comment]
water level has been fixed in latest "usgs" push.

 actually I am wondering if the "alpine" and the "water level" settings are redundant now. they should almost never be needed unless no biome file is present. i guess it doesn't interfere and if it does the levels can be adjusted out of range.

**Comment by bobombolo** [comment]
it costs some generation time but here is a biome with alternate ground cover, shrubs and trees:
![screenshot_20151111_193217](https://cloud.githubusercontent.com/assets/12679496/11109943/310b9874-88ab-11e5-8ee6-6fc4fdc6f68f.png)

**Comment by bobombolo** [comment]
slightly different settings. might leave this in for biome 0.  
![screenshot_20151111_194020](https://cloud.githubusercontent.com/assets/12679496/11110044/228e6172-88ac-11e5-9d97-5f8827faf5c1.png)

**Comment by bobombolo** [comment]
usgs lclu codes pushed to master

**Comment by bobombolo** [comment]
might still need a roads layer since there is no explicit roads category in the usgs classification system
