### ISSUE TITLE
magicwand not found on Windows

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#38]
current master switched from loading magick from luarocks to accessing it directly. In Windows it now throws an error when magick is trying to load MagickWand
magick/init.lua:163 Failed to load ImageMagick(MagickWand)
in function 'try_to_load'
in function 'require'
realterrain\init.lua:23

is the newly bundled magick lua code good to go, or do I need to do something?

**Comment by Tank-ACiD** [comment]
See changelog below for this and additional minor issues.

Changelog Nov 15th, 2015

[magick not loading in Windows]
switched back to using luarocks

[typo]
realterrain.settings.b2shrub = "default:dry_grass_1"

[err was not defined]
imagesize.lua:40
local file, closefile, origoffset, err

[file changed to filename , 3x]
realterrain/init.lua
realterrain.list_images()
--Windows
table.insert(list, filename)
...and in...
realterrain.list_schems()
--Windows
if string.find(filename, ".mts", -4) ~= nil then
	table.insert(list, string.sub(filename, 1, -5))
end
			
[added error checking for values outside of biome index range]
...for now this fixes biomes with values > 9 until dynamic value range is supported
realterrain.settings.max_biome = 9
realterrain.settings.max_water = 9
realterrain.settings.max_road = 9

minetest.register_on_generated(function(minp, maxp, seed)
if biome > realterrain.settings.max_biome then
	biome = 0
end
..also added for water and roads

**Comment by Tank-ACiD** [comment]
[commented out non-existent function call]
minetest.register_on_player_receive_fields(function(player, formname, fields)
--biome config form
--realterrain.init()

**Comment by bobombolo** [comment]
implemented those fixes thanks.

at least with the current script we have three choices for image libraries... magick, luarocks magick, or imlib2 if 16 bit is not required...

**Comment by Tank-ACiD** [comment]
agreed. for now a system call to ImageMagick's Identify.exe is property
getting me pixel bit depth and it is rendering the 16bit dem, just not sure
on accuracy as I went back to all 8 bit for testing.

**Comment by bobombolo** [comment]
but is it handling float 16bit? i doubt it.

**Comment by bobombolo** [comment]
hey I opened the DEM of yours into QGIS and used RASTER->TRANSLATE to re-output it and it saved as a geotiff that works just fine in realterrain. so that is solved.

**Comment by bobombolo** [comment]
as for the accuracy, the derived dem i created in Qgis has a different range, the original was from 42m to 482m and the derived was from 36m to 462m but the top-left pixel is 387m in both cases and that is the exact height of the voxel in minetest!

**Comment by bobombolo** [comment]
this topic has been hijacked from #26

**Comment by bobombolo** [comment]
this is still an issue, line 163 of magick/init.lua needs to be altered...

**Comment by bobombolo** [comment]
#45 will handle this and other library issues
