### ISSUE TITLE
OOM 

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#39]
using remote

2015-11-11 11:41:44: ERROR[main]: ServerError: Lua: OOM error from mod 'realterr
ain' in callback ScriptApiEnv::environment_OnGenerated(): not enough memory
2015-11-11 11:41:44: ERROR[main]: Current Lua memory usage: 61 MB

crashed after a few seconds of mousing over the images in the selection window that displays the biome available node types.

**Comment by bobombolo** [comment]
weird.
i'm going to refactor the biome system today to handle absolute values for pixels, load unique values, save biome settings to a separate config file, have a default config file, handle multiple screens of biomes so we can handle a few dozen, etc.
it's canadian veterans day today, no work.

**Comment by Tank-ACiD** [comment]
right on! its crashing on me now, regularly, even without using the remote
and at less memory values, like 25MB
I'm going to remove all trees and land cover to see if it helps. I'm trying
to get it all working on windows so I can grab some more screen shots over
what you have posted on the project to fill out the presentation that I
have to have ready by 4pm tomorrow.

**Comment by bobombolo** [comment]
i am unable to recreate this crash

**Comment by bobombolo** [comment]
btw i have to restart minetest from time to time, even reboot, rarely

**Comment by bobombolo** [comment]
see if this OOM error still happens with the USGS branch that only opens two files instead of 4

also i cleaned up the main form a bit

![screenshot_20151111_171901](https://cloud.githubusercontent.com/assets/12679496/11108071/9a0804ec-8898-11e5-8341-ad211e94f6fc.png)

**Comment by Tank-ACiD** [comment]
will do prob tomorrow, going to have to crunch in the next 4 hours to put
this powerpoint together.
