### ISSUE TITLE
Missing screenshot and description files

### ISSUE THREAD

**Issue by ExcaliburZero** [bobombolo/realterrain#4]
Currently this mod does not have a proper screenshot or description file included. Both are used when displaying the mod in the Mods tab of the main menu of Minetest.

The screenshot should be in a 3:2 aspect ratio, be named "screenshot.png", and be placed in the main directory of the mod.

The description file should be a small text file with a short description of the mod, be named "description.txt", and be place in the main directory of the mod.

**Comment by bobombolo** [comment]
![screenshot_20151019_145505](https://cloud.githubusercontent.com/assets/12679496/10593425/9080cd78-7678-11e5-9b18-f883387874cc.png)

**Comment by bobombolo** [comment]
![screenshot_20151019_202537](https://cloud.githubusercontent.com/assets/12679496/10597094/fa84812a-769f-11e5-822e-d0aa8b7f6e6d.png)
