### ISSUE TITLE
no-shrub option

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#40]
you can set a blank space for tree = no tree, need something to allow for no shrub.

**Comment by bobombolo** [comment]
yeah since it is an image select... maybe an "X" next to the image.

**Comment by bobombolo** [comment]
implementing a no shrub option is difficult. I think the solution is to simply set the probability to 0

**Comment by Tank-ACiD** [comment]
ok, as long as the function exits asap based on a value of 0 just to save
rendering time.

**Comment by bobombolo** [comment]
i will add a check for probabilities in the tree and shrub subroutines
