### ISSUE TITLE
form crashes with certain files present

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#42]
when i try to use the full Ryan dataset the game crashes when I use the settings tool with the error:

Runtime error from mod 'realterrain' in callback item_OnUse(): /home/danjor/.minetest/mods/realterrain/init.lua:233: attempt to index a nil value

resetting the rasters folder and the settings file fixes the problem. cannot figure this out

**Comment by Tank-ACiD** [comment]
that fix is listed in my changelog... i have a biome value > 9

it's not a nil value, its an array value that's not defined since we
hardcode biomes 0..9

**Comment by bobombolo** [comment]
i applied that fix. this is something different that only happens when I am trying to load your full dataset and it happens in the "list_images" section...

**Comment by bobombolo** [comment]
i thought it had to do with sub-folders in the raster folder but it doesn't

**Comment by Tank-ACiD** [comment]
weird, all i did was change 'file' to 'filename' in two places
  for file in io.popen('find "'..RASTERS..'" -type f'):lines() do

local filename = string.sub(file, #RASTERS + 1)
local im = imagesize.imgsize(RASTERS .. filename)
if im then
table.insert(list, filename)
end
im = nil
end

**Comment by bobombolo** [comment]
i also applied that fix. this is some strange timeout thing i think, with large files the loop breaks or something.

**Comment by Tank-ACiD** [comment]
weird, i mean it shouldnt... esp if you are in unix...code shouldnt get
there

**Comment by bobombolo** [comment]
i know. i have a hard time debugging this one...

**Comment by bobombolo** [comment]
can't recreate
