### ISSUE TITLE
color overlay and band overlay for false-color (using 216 colors)

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#60]
even with 216 websafe colors we might be able to take landsat images and display the raster as a 3D composite of raster bands.

we could also simply have an image mapped onto the surface of the land. this could be a cool way to expand the https://forum.minetest.net/viewtopic.php?f=9&t=6751 and have a non-biome way of colorizing a DEM

**Comment by Tank-ACiD** [comment]
yes, directly rendering a raster's color value in MT would be valuable.
There are also predefined combinations
that would be nice to offer the user

http://web.pdx.edu/~emch/ip1/bandcombinations.html

I believe the current landsat is the same as 7..I'll have to check on that.

**Comment by bobombolo** [comment]
yes to do it properly would be impossible since it would require millions of textures. maybe even 216 would do a decent aproximation. yeah it would be cool to allow raster band combinations. it would actually be easy, except, once again we are adding 3 more large files to the magick cache. i have been crashing a lot lately on large files...

**Comment by bobombolo** [comment]
do you have landsat bands for your study area?
also, short of doing a classification of your study area to generate lclu raster for your study area, could you reclass the biomes layer you made to eliminate class 1 and 5, then superimpose your roads layer onto it as class 1(pixel value 1 or 10-19)  and your rivers layer as class 5 (pixel value 5 or 50-59)? it only needs to be 8 bit.

**Comment by bobombolo** [comment]
http://stackoverflow.com/questions/19782975/convert-rgb-color-to-the-nearest-color-in-palette-web-safe-color

**Comment by Tank-ACiD** [comment]
I have 30m landsat for the region, yes. I can leave it lik ethat or
interpolate to 1m like I have been.

I'll reclassify values 1 and 5 and merge the roads/rivers and get that to
you tomorrow for sure

**Comment by bobombolo** [comment]
30m matches the dem doesn't it or is your dem 1m? all my dems are 30m

**Comment by Tank-ACiD** [comment]
the mv- rasters are all 1m resolution, hence why they are so big :)

**Comment by bobombolo** [comment]
ya they are. another feature I could consider is separate offsets and scales for each raster (biome, input) the only challenge there is fitting it in the form but otherwise it's easy.

**Comment by bobombolo** [comment]
any idea how this numbering system translates to utm grids just looking at it? ftp://ftp2.cits.rncan.gc.ca/pub/geott/landsat_7/ortho/geotiff/utm/

**Comment by bobombolo** [comment]
here is a preliminary grayscale mode for mapping an image onto the map, in this case i mapped the dem back onto itself:

![screenshot_20151129_192733](https://cloud.githubusercontent.com/assets/12679496/11462895/5d68e340-96cf-11e5-8ad5-5be016e8849c.png)

color mode coming very soon

**Comment by bobombolo** [comment]
duuuuuuuuuude!
![screenshot_20151129_200807](https://cloud.githubusercontent.com/assets/12679496/11463363/2ecb5c24-96d5-11e5-8cf3-2b305198eac3.png)
source image:
![antenn01 resized](https://cloud.githubusercontent.com/assets/12679496/11463370/43420fea-96d5-11e5-88f5-34470603b7c9.jpg)

**Comment by bobombolo** [comment]
multiple band combinations soon

**Comment by bobombolo** [comment]
![screenshot_20151129_202539](https://cloud.githubusercontent.com/assets/12679496/11463515/c46edae2-96d7-11e5-926b-5990516f4184.png)

**Comment by Tank-ACiD** [comment]
ok mvbiomes.tif is as requested, i'll share on google drive. wasted 2+ hrs
today tryign to figure out why my raster calculator wasn't working, come to
find out I've got the geodatabase opened in ArcCatalog so there was a file
lock...grumble.

**Comment by Tank-ACiD** [comment]
try here
https://drive.google.com/file/d/0B7RDNPUdrkvQRE5ETjRFTG92cHc/view?usp=sharing

**Comment by bobombolo** [comment]
multiple band overlay now possible!

![screenshot_20151130_195856](https://cloud.githubusercontent.com/assets/12679496/11492216/d07bfd52-979e-11e5-9593-9d801abbc98f.png)
![screenshot_20151130_195859](https://cloud.githubusercontent.com/assets/12679496/11492217/d0813f6a-979e-11e5-872c-c7d68b964ade.png)

**Comment by bobombolo** [comment]
need to add form validation for these modes

**Comment by bobombolo** [comment]
![screenshot_20151201_201522](https://cloud.githubusercontent.com/assets/12679496/11522096/61d65c38-9868-11e5-82a9-b7532c015db9.png)

**Comment by bobombolo** [comment]
the game slows down a lot when using these 216 textures. it doesn't seem to effect anything if they are not used but still loaded as node types and sit in the textures folder.

**Comment by bobombolo** [comment]
could try something simple like this but expanded to use all default node types: https://github.com/kaeza/minetest-imageloader/blob/master/palette.lua#L83-L100

**Comment by Tank-ACiD** [comment]
http://landsat.usgs.gov/band_designations_landsat_satellites.php

**Comment by bobombolo** [comment]
![visible_spectrum_waves_big](https://cloud.githubusercontent.com/assets/12679496/11549127/2a2ec512-9918-11e5-90da-8814823af766.jpg)

**Comment by bobombolo** [comment]
i can't get a combination that looks like rgb. not sure if it is an issue with my band combinations or the code or the source rasters.

**Comment by bobombolo** [comment]
here are the results of some combinations I have tried

![screenshot_20151202_171651](https://cloud.githubusercontent.com/assets/12679496/11549191/da723b52-9918-11e5-8f7a-40da6d4d79ac.png)
![screenshot_20151202_171820](https://cloud.githubusercontent.com/assets/12679496/11549192/da7884a8-9918-11e5-9fe1-b7cfafcd78b6.png)
![screenshot_20151202_171906](https://cloud.githubusercontent.com/assets/12679496/11549193/da7c75a4-9918-11e5-8c2d-615740fee13b.png)

**Comment by bobombolo** [comment]
![screenshot_20151202_172512](https://cloud.githubusercontent.com/assets/12679496/11549310/c5cbc30c-9919-11e5-89b7-555ee8b0f966.png)

**Comment by bobombolo** [comment]
![screenshot_20151202_172703](https://cloud.githubusercontent.com/assets/12679496/11549324/eab2aed8-9919-11e5-9bda-cffcab36493d.png)

**Comment by bobombolo** [comment]
course none of them looks to natural rgb in "websafe" mode

**Comment by bobombolo** [comment]
see #74

**Comment by Tank-ACiD** [comment]
well, if you zoom far enough out.... :)

**Comment by bobombolo** [comment]
have you managed to use it?

**Comment by bobombolo** [comment]
https://forum.minetest.net/viewtopic.php?f=7&t=13744

**Comment by bobombolo** [comment]
apparently textures can be modified and "created out of thin air" so to speak:

http://dev.minetest.net/texture#Texture_grouping

colorize in particular

**Comment by bobombolo** [comment]
used like this:
<pre>
minetest.register_node("test:node", {
   tiles = {"default_stone.png^[colorize:red:120"},
   description = "Node test",
   groups = {crumbly=3},
})
</pre>

**Comment by bobombolo** [comment]
red can be a color code like FF8899

all the nodes still have to be registered aforehand... so it doesn't help MUCH, but testing huge numbers of colors would be easier to do programmatically this way rather than generating colored pixels as textures and building a modpack for them to go in...

**Comment by bobombolo** [comment]
i suppose that the color overlay layer could be scanned for pixel values and the only those colors could be registered as nodes...

**Comment by bobombolo** [comment]
this works! however there is still the issue of the time it takes to register thousands of nodes... seems prohibitive. websafe colors it is...

**Comment by bobombolo** [comment]
color overlay is broken in native bmp mode, only red is retrieved: 

![screenshot_20151213_114008](https://cloud.githubusercontent.com/assets/12679496/11768852/5c0f305c-a18e-11e5-87eb-1b3eecd3c165.png)

**Comment by bobombolo** [comment]
build_heightmap() doesn't handle G and B channels yet

**Comment by bobombolo** [comment]
ok enumerate mod in build_heightmap now handles r,g,b

there is some fill_below bugginess happening in all modes though:

![screenshot_20151218_211814](https://cloud.githubusercontent.com/assets/12679496/11911517/0ac2f5c4-a5cd-11e5-8911-27f283636229.png)

**Comment by bobombolo** [comment]
perhaps there are better pallets to use for a limited set of colors that is better than websafe. websafe colors have a lot of dull greys. i was thinking it would be cool to do a histogram on the raster to be used for color overlays but this would have to be done at mod startup in order to register the nodes. this is a small matter since after changing the raster most sane people would delete map.sqlite and restart the map anyway, so it could work. then the top 256 colors could be made as color nodes. this would probably have a very good result. it would be more complex for three individual channels for r,g,b but would still work. the tricky part would be approximating the less-common colors, or those outside of the pallet. color-distance computation is a whole nother topic and could be computationally costly... it would be worth a try anyway...

another option would be to have image/graphics-magick do a color depth reduction WITH DITHERING. but this is less optimal since it would require making a copy of possibly large rasters, and requires one of these two libraries. also the result might still be rather poor, still stuck with using the same websafe pallet.

**Comment by bobombolo** [comment]
this feature is good enough. trying to register a set of custom nodes based on a histogram is more of a challenge than a good idea for a feature. for one thing the map would be even less transferable without the source image. at least as it is now if the mod is active then the 216 websafe colors will make the map viewable.
