### ISSUE TITLE
dark areas in generation that don't heal on map restart

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#68]
need to figure out what these are, how to fix them, and how to avoid them.

**Comment by Tank-ACiD** [comment]
only started happening now, last master (init.lua) I used was
created/downloaded 11/10/2015 10:40pm

**Comment by bobombolo** [comment]
yeah it has been happening for a while for me so I will compare the code from that commit. i think it might have to do with generating sky blocks differently. i have something to check into anyway.

deleting the map is the only way to fix them. of course now that I want some I can't make them happen.

**Comment by bobombolo** [comment]
it seems like if you start above the map and start heading down as soon as you can the dark spots appear.

![screenshot_20151202_172458](https://cloud.githubusercontent.com/assets/12679496/11549294/aa780c3c-9919-11e5-92c1-1009a5f7ad8f.png)

**Comment by bobombolo** [comment]
ok I just pushed a new master that does some stuff to sky blocks that I was skipping in order to speed things up. I may have to do the same thing to off-raster and sub-surface chunks eventually. it is too bad because those were only taking 1ms to not-generate and now they take 100ms. oh well...

the missing lines were:

<pre>
vm:set_data(data)
vm:calc_lighting()
vm:write_to_map(data)
vm:update_liquids()
</pre>

**Comment by bobombolo** [comment]
another thing to try before updating from master, activate the worldedit mod and use the //fixlight command on a volume defined by pos1 and pos2 that encloses the dark patch

**Comment by Tank-ACiD** [comment]
prob the calc lighting :) maybe you can skip them sky blocks if the are
more than 1 above surface?

**Comment by bobombolo** [comment]
that's what i was doing. actually it goes by chunks which is 80x80x80 and if it was completely empty it was skipped, but that is not acceptable apparently.

**Comment by bobombolo** [comment]
the strange thing is that it only happens sometimes.

**Comment by Tank-ACiD** [comment]
probably a bug in minetest

**Comment by bobombolo** [comment]
reopen if you see this again
