### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#70]
I am testing server mode compatability, and came across this, which is probably unrelated to being client-server but none the less it was produced while in that mode. I had just logged into an existing world and was moving aroud.

20:30:52: WARNING: Assignment to undeclared global "get_input2" inside a functio
n at I:\Minetest\bin\..\mods\realterrain\init.lua:692.
20:30:52: WARNING: Assignment to undeclared global "get_input3" inside a functio
n at I:\Minetest\bin\..\mods\realterrain\init.lua:693.
20:30:52: WARNING: Assignment to undeclared global "get_input_color" inside a fu
nction at I:\Minetest\bin\..\mods\realterrain\init.lua:694.
20:30:52: WARNING: Assignment to undeclared global "fill_below" inside a functio
n at I:\Minetest\bin\..\mods\realterrain\init.lua:695.
20:30:52: WARNING: Assignment to undeclared global "moving_window" inside a func
tion at I:\Minetest\bin\..\mods\realterrain\init.lua:696.

**Comment by bobombolo** [comment]
i think i fixed those since yesterday, is that your latest master?

**Comment by Tank-ACiD** [comment]
no, it looked a day old so I didn't grab, i will grab the latest
