### ISSUE TITLE
grass/tree gen conflict

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#71]
when a tree generates on a node that already has grass, it begins above the grass. it should overwrite the grass. So, some sort of collision detection should be added

**Comment by bobombolo** [comment]
wow i hadn't caught that visually! i'll check it out.

**Comment by bobombolo** [comment]
sure enough! hadn't seen one till i looked for it.
![screenshot_20151203_214730](https://cloud.githubusercontent.com/assets/12679496/11582785/77efaa42-9a07-11e5-9844-f1c4bd574afb.png)
fixed in latest master
