### ISSUE TITLE
16bit DEMs are no longer generating properly

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#72]
I'm using dem16.tif and the mvbiomes.tif. I have them set to 16 and 8 bit respectively in the tool,
I exited and deleted map.sqlite, logged in to a flat-ish world

the world is very very flat. 0,0 is capped at 257.5 and going to 4170,1,-18950 is the middle of the map which should be way higher than 0.5. I actually cannot find any increase in surface elevation but there must be if I went from 257 to 0 via teleport

I see visual indication on the surface of a biome change, which is based on elevation, yet the game has no elevation change to the surface as is expected

8-bit DEM seems to render fine.

**Comment by bobombolo** [comment]
i had to open the dem into QGIS then save it again. which I always had to do for things to work. also try latest master.

**Comment by bobombolo** [comment]
sorry i thought you meant the mv dem (i always have to resave that one). you are referring to demo/dem16.tif right? I just tested it and it seems to work fine for me (huge step sizes)

you might have caught a commit where imlib2 was the default PROCESSOR. this is now line 1 in the code to make it easy to change. make sure you are on magick.

sorry did a lot of commits today

![screenshot_20151203_214211](https://cloud.githubusercontent.com/assets/12679496/11582705/c3c53708-9a06-11e5-94bd-5ca36d6a9bdc.png)

and here is your mv/dem (resaved) with mv/biomes

![screenshot_20151203_214433](https://cloud.githubusercontent.com/assets/12679496/11582753/2477cb6a-9a07-11e5-9d30-974dc3ac8081.png)

**Comment by bobombolo** [comment]
is this still an issue?

**Comment by Tank-ACiD** [comment]
let me check the latest master...

**Comment by bobombolo** [comment]
make sure you change the default processor from native to magick.

**Comment by Tank-ACiD** [comment]
Still an issue. I have realterrain configured to use magick (edited first line only)

I created a new 16big dem and accompanying 8 bit biomes file in ArcMap, ran MT, saw that the default world dem and biomes was rendering properly. I changed the settings files to load those 2 new ones, set the proper bit, and reset the world using the button. New world is completely flat and only 1 biome.

**Comment by Tank-ACiD** [comment]
the entire world is biome 1

**Comment by Tank-ACiD** [comment]
using magick library to read the 16bit dem ..this is very strange...
code 1392:
				if PROCESSOR == "magick" then
					r,g,b = realterrain[rastername].image:get_pixel(x, z) 
					print(realterrain[rastername].bits.." raw z: "..r)
					r = math.floor(r * (2^realterrain[rastername].bits))
					g = math.floor(g * (2^realterrain[rastername].bits))
					b = math.floor(b * (2^realterrain[rastername].bits))
					print(realterrain[rastername].bits.." real z: "..r)

produces this over and over...
16 raw z: 0.031372549019608
16 real z: 2056
8 raw z: 0.094117647058824
8 real z: 24

**Comment by bobombolo** [comment]
yes i did the same thing last night and was so perplexed that I just 
went to bed. i think that imagemagick simply fails to read those pixel 
values. graphickmagick reads them no problem.

**Comment by Tank-ACiD** [comment]
haha i wish i had done the same, i was so perplexed i didn't go to bed.
now..i'm thinking i should get a few hours sleep so i can think straight.

**Comment by bobombolo** [comment]
i added an option for magick, MAGICK_AS_CONVERT for people who can't get gm lib installed, but want the speed of a lib and have the magick lib installed, that gives the benefit of automatic bit depth detection at the slightly slower speed (compared to using magick like imlib2 or native mode -- pixel access). when enumerating pixels, magick lists 16-bit numbers as a percent and 8bit as their actual value...
still, GM is the best, as it is faster and handles arcmap rasters without conversion...
