### ISSUE TITLE
python issues

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#73]
python cannot at this time get rgb for imageoverlay mode:

http://stackoverflow.com/questions/11064786/get-pixels-rgb-using-pil

also it simply returns nil for some rasters. no saying which ones or why yet...

**Comment by bobombolo** [comment]
actually it is related issue, it doesn't like rgb images unless you convert to rgb mode.

**Comment by Tank-ACiD** [comment]
may have to just stick to single band images for now...

**Comment by bobombolo** [comment]
fixed

**Comment by bobombolo** [comment]
in the PIL color is "RGB", 16bit is "I;16" and 8-bit is "L"
mode list-ish: http://svn.effbot.org/public/tags/pil-1.1.4/libImaging/Unpack.c

this is actually not a bad way to generate. it looks slow on the profiles for each block but it seems to stack the processing or something because it generates reasonably quickly
