### ISSUE TITLE
get native tiff processor working better

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#76]
I have re-integrated the original direct-tiff decoding from the first versions of the mod so that SOMETHING works out of the box. it is mostly working but there are alignment issues due to not handling the file header length perfectly. solving this could mean it is not much work to handle 16-bit tiffs directly as well. 
![screenshot_20151205_061903](https://cloud.githubusercontent.com/assets/12679496/11608241/a7411ca6-9b18-11e5-812f-9546b7e4f490.png)

**Comment by bobombolo** [comment]
ok the current master has default tiff mode enabled. there is still some misalignment but much less than before. also 16 bit mode is rendering sensible maps but still with slices of misalignment and some x/z distortion here are some screenshots:

remaining 8bit misalignment:
![screenshot_20151205_180000](https://cloud.githubusercontent.com/assets/12679496/11611279/0e1b33ba-9b7a-11e5-88fb-c17e4bfefe73.png)
16bit (scaled by 0.3) misalignments:
![screenshot_20151205_174942](https://cloud.githubusercontent.com/assets/12679496/11611281/2271d24c-9b7a-11e5-86ca-e6a8448714f5.png)

![screenshot_20151205_174718](https://cloud.githubusercontent.com/assets/12679496/11611284/2ca85c22-9b7a-11e5-8ff6-d2f412805817.png)

**Comment by bobombolo** [comment]
this all seems like simple arithmetic

**Comment by bobombolo** [comment]
good gen times:

311 ms  mapchunk (7, 1, -6)
[GEN] 353 ms  mapchunk (7, 1, -5)
[GEN] 731 ms  mapchunk (6, 2, -6)
[GEN] 493 ms  mapchunk (6, 2, -5)
[GEN] 849 ms  mapchunk (7, 2, -6)
[GEN] 612 ms  mapchunk (7, 2, -5)
[SKY] 71 ms  mapchunk (5, 2, -5)
[GEN] 770 ms  mapchunk (5, 2, -6)
[GEN] 573 ms  mapchunk (5, 2, -4)
[GEN] 560 ms  mapchunk (5, 1, -4)
[GEN] 734 ms  mapchunk (4, 2, -6)
[SKY] 55 ms  mapchunk (4, 2, -5)

**Comment by bobombolo** [comment]
using the test.tif file (a grayscale file) the output looks like this:

![screenshot_20151213_165047](https://cloud.githubusercontent.com/assets/12679496/11770703/f6cbcf94-a1b9-11e5-951a-13b67ce38dee.png)

for fun here it is in rgb (doesn't at all anticipate 3 channels):
![screenshot_20151213_164749](https://cloud.githubusercontent.com/assets/12679496/11770705/ffa73252-a1b9-11e5-9d9a-0fe47ddd458b.png)

**Comment by bobombolo** [comment]
8-bit native tiff processor working very well. no junk pixels remain:

![screenshot_20151223_170314](https://cloud.githubusercontent.com/assets/12679496/11987606/14d3316e-a997-11e5-9b25-cf3c14c2d244.png)

**Comment by bobombolo** [comment]
no amount of visual debugging is getting me closer to understanding the 16-bit tiff problem. each pixel is a different height, which makes no sense as there are only two different values in this raster. 

![screenshot_20151223_175809](https://cloud.githubusercontent.com/assets/12679496/11988082/eb6307ca-a99e-11e5-88d0-4744d252a805.png)

i certainly could be multiplying the wrong byte as the larger portion of the number but i have tried both. anyone who wants to take a crack at it can fiddle with this code. the 8-bit code immediately above it works.
https://github.com/bobombolo/realterrain/blob/master/init.lua#L1308-L1318

maybe there is some interlacing? or a spacer character, but i doubt that.

**Comment by Tank-ACiD** [comment]
looking into it....just for giggles you do need to elseif for 16, as the
tiff can also be 2 , 4, and 32 bit :)

**Comment by bobombolo** [comment]
well the dropdown in the form is what is determining that number and it only does 8/16 manual bit-depth detection.

**Comment by Tank-ACiD** [comment]
also I thought the multiplier was 65535? elevation looks much lower but you
may be floating at a different position? 14 versus 7? is the outer surface
ring at the same height on both, just the 16 has 'noise'?

**Comment by bobombolo** [comment]
the multiplier is 65535 when the source value is a float between 0 and 1
when the source is two bytes the first byte is 0-255 and the second byte is multiples of 256, nes pas?
anyway as for the test raster, test-gray16.tif, i saved that in photoshop which is the only graphic program I have that will even open a 16 bit image, and yes it may very well have screwed up the image with noise. that would be a problem. haha.

**Comment by bobombolo** [comment]
this is all purely for the fun of it at this point...

**Comment by bobombolo** [comment]
the intended value is outer ring 5 and inner core 10

**Comment by bobombolo** [comment]
actually the implementation in master seems to work within the center of the default raster, at least it results in something sensible: this is the dem16.tif with yscale set to 0.01. the biome file seems to be distorted (flattened in x/z) and does not register to the dem properly, which is odd since it is using the native bmp processor... 
![screenshot_20151223_191802](https://cloud.githubusercontent.com/assets/12679496/11988918/25806316-a9aa-11e5-8e7b-f96d801259b9.png)

there is lots of junk around the outside of the file. which leads me to believe that each tiff file can have a different amount of header info and other junk before the pixel data. with 8 bit tiffs this seemed to be limited to 8 bytes, but that might just be with the files I had. here you can see that the first few "rows" are jibberish but the trailing edge of the raster has a clean cut:

![screenshot_20151223_192319](https://cloud.githubusercontent.com/assets/12679496/11988952/b4ce957e-a9aa-11e5-8d29-c290f3368b3f.png)

actuallyif I offset the read function to the distance of the jibberish (5541*2) then the output is clean. this does not work on the test raster though, which means we have different header lengths. the headers appeared to be at the end of the file for files created by other software, so this could be a big task of hacking imagesize to return the position of the headers, which is something i had done before I discovered most of the headers to be at the end of the file...

also there is no explanation why the biomes are distorted in z/x

**Comment by bobombolo** [comment]
trying your LQ rasters gives complete jibberish... so i dunno, this is why we went to magick in the first place... waste of time, too many factors, byte order, interlacing, header lengths, header positions, etc.
