### ISSUE TITLE
computed maps (fractals, polynomials)

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#79]
for fun I want to add a mode for computed terrains that will turn the mapgen into a 3D graphing calculator and a fractal viewer. 
this is for the development branch only
start with a colorized mandelbrot fractal
and
a polonomial (cubes)

**Comment by Tank-ACiD** [comment]
cool!

**Comment by bobombolo** [comment]
need to colorize more creatively, might include these in the upgraded symbology form...
http://www.fractalforums.com/programming/newbie-how-to-map-colors-in-the-mandelbrot-set/

grey results:

![screenshot_20151208_182205](https://cloud.githubusercontent.com/assets/12679496/11674901/f744095c-9dd9-11e5-95a9-e1f4dcde86ae.png)

**Comment by bobombolo** [comment]
it would be cool if diving down into the brot would start a new brot on the coordinates of the above brot, so that there is a form of zooming. though this would not be reapeatable without deleting the map, and since resolution will never improve. currently the realterrain scale settings are used. need to be set to 0.02 or less to be anything recognizable.
another way of doing the zooming would be to punch one of the pixels and then that would be the center for the next dive...

**Comment by bobombolo** [comment]
also the setting of an altitude to the brot pixel values is as difficult as making a nice color gradient.

**Comment by bobombolo** [comment]
![screenshot_20151208_202400](https://cloud.githubusercontent.com/assets/12679496/11676683/b47a9c3e-9de9-11e5-882c-90b8bf0bb31a.png)

**Comment by bobombolo** [comment]
![screenshot_20151208_203644](https://cloud.githubusercontent.com/assets/12679496/11676812/71151db4-9deb-11e5-9835-f77e6befb2d0.png)
large holes in the black area for some reason

**Comment by bobombolo** [comment]
polynomial mode:
with fillbelow turned on:
![screenshot_20151211_195543](https://cloud.githubusercontent.com/assets/12679496/11760113/99b28d0c-a042-11e5-86ac-7f977de8b178.png)
with fillbelow turned off which is the way it is in master now
![screenshot_20151211_200127](https://cloud.githubusercontent.com/assets/12679496/11760117/b52ca5f4-a042-11e5-9b74-587ffddcd14d.png)
the settings for this draw:
![screenshot_20151211_200757](https://cloud.githubusercontent.com/assets/12679496/11760127/e2faeefa-a042-11e5-85b5-f58409dd2fe9.png)

wasn't going to add these to master but again there were so many improvements to the forms and other logic that I had to... for example, different output modes now only show the relevant fields, as with different processors, so that those processors (gm, py) that don't need bit depth to be set, don't show bit depth, etc.

**Comment by Tank-ACiD** [comment]
looks great

**Comment by bobombolo** [comment]
![screenshot_20151211_201910](https://cloud.githubusercontent.com/assets/12679496/11760176/a4582dc8-a044-11e5-8cf8-fed71a9dfbee.png)

**Comment by bobombolo** [comment]
these are easter-eggs and though more features could be built for them that is for a much later time.

**Comment by bobombolo** [comment]
paramat has added a fractal mapgen to core.
