### ISSUE TITLE
edge bug in native processor

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#80]
must be missing the raster by one
![screenshot_20151208_193846](https://cloud.githubusercontent.com/assets/12679496/11676035/7986f7c2-9de3-11e5-90b8-68e930a734c2.png)

**Comment by Tank-ACiD** [comment]
my 16 dems have been doing this on the north edge (row 1), I think I posted
an image many issues ago.

**Comment by bobombolo** [comment]
and that's the magick library doing that? is that the 16bit resaved version that I uploaded (from qgis) or is that something exported straight from arcmap?

**Comment by Tank-ACiD** [comment]
right from arcmap

**Comment by bobombolo** [comment]
oh i thought we had that issue where they don't even render because they appear to be floats?
