### ISSUE TITLE
border of zero around map

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#87]
tried to fix this but it needs testing to see if we are losing data. it's a confusing issue for being only one pixel...

**Comment by bobombolo** [comment]
ok solved the problem with a test raster with a one pixel wide border of value 5 and the inside being value 10 and the raster is 10x10
![screenshot_20151213_150907](https://cloud.githubusercontent.com/assets/12679496/11770107/a942ed38-a1ab-11e5-9f77-06ce5619154e.png)

**Comment by bobombolo** [comment]
the benefit is that pixels no longer are drawn on the x=0 or z=0 axis in the game, so they go from 1 to width and -1 to -length, which is more logical. test the latest master to see if this fixes things.

**Comment by bobombolo** [comment]
oh great, that was using the native processor, using magick the result is worse than before, they must index pixels differently, starting at 1 and 0 respectively

![screenshot_20151213_151300](https://cloud.githubusercontent.com/assets/12679496/11770131/1e3a63c8-a1ac-11e5-9a4b-a821ddcfec81.png)
the truly strange thing is that the elev = 5 shelf is extended for two blocks? does magick take the edge value?

**Comment by bobombolo** [comment]
apparently it does because here is the result from imlib2 which makes more sense. so yeah, each processor needs a different offset... no wonder this issue has been so hard to track down...

![screenshot_20151213_151522](https://cloud.githubusercontent.com/assets/12679496/11770139/7028d1b0-a1ac-11e5-8fbc-b16fcf89789a.png)

**Comment by bobombolo** [comment]
OK, again, graphically I have managed to get the native, imlib2 and magick processors working. not sure how scales effect this but phew, i guess it is working for now.

**Comment by Tank-ACiD** [comment]
that's going to be the issue when supporting more than one solution, but
workable with enough configuration. Along this same line, what are we doing
about NULL values? We should have embedded checking for NULL, and convert
it to 0 or some abstract negative value below the minimum elevation value.
I would think a 0 is fine since it's a world-wide reference elevation.
Maybe also reserve/create a custom voxel texture for NULL nodes, not
choose-able in the menu system.

**Comment by bobombolo** [comment]
i have debugged this issue for all modes except "convert" so I trust it now (pushed to master). "convert" mode uses the build_heightmap which needs total overhaul anyway. also native mode for tiffs hasn't been tested but it has other alignment issues as well.

null / nodata values:

right now they just don't get rendered, but that is only when they are off-raster. there can't really be null values in a raster, so they are always going to be a nodata value. for now we can assume that 0 is the default value, which it is for many situations, such as color overlay, to avoid crashes. handling nodata values in raster i something I want to package into our developing the use of GDAL. In py mode I am populating a "nodata" attribute for rasters that contain metadata, and it would be easy to implement that as well, simply not rendering anything in that node column when it is encountered. we could also add a field that explicitly sets a nodata value for rasters that gdal can't get the information from, but most rasters, other than geotiffs, don't handle negatives very well, for example, I have some raw DEMs that magick handles, but python image library won't handle because it can't deal with signed 16 bit rasters, so this nodata/negative values issue might be a pain which I think in the past we agreed is an edge case we shouldn't worry about too much at this juncture.

**Comment by bobombolo** [comment]
raster output also not showing the strange border issue anymore either...
![screenshot_20151213_164105](https://cloud.githubusercontent.com/assets/12679496/11770638/759e9128-a1b8-11e5-9ba5-08ef51b47035.png)

**Comment by bobombolo** [comment]
only happening now with imlib2 on south and east edges
