### ISSUE TITLE
biomes (groundcover)

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#9]
do we want to have settings for the different cover layers or do we want to do it by naming convention? Do we want to have one file with different channels, and different values representing different kinds of cover or different files? probably a combination of different files and different values but not different channels. and for future convenience probably set by settings in-game. this allows for ease of creation, and easy of change.

required fields for cover files:
-biomes, break values for different biomes which will determine default ground, grass, shrub, trees
-vegetation: break values for grass, shrubs, trees which will explicitly place specific items (may be redundant to biomes but use cases for both are easy to imagine)
-human: break values for roads, different building heights, signs, chests, other items
-water: rivers and lakes

OR

files for the following layers
biomes
trees
water
roads
AND
buildings (top-left corners) with break values for building type (mts import)
item placement (break values for item type)

**Comment by bobombolo** [comment]
biome painting, water painting, road painting, somewhat implemented:

![screenshot_20151020_141450](https://cloud.githubusercontent.com/assets/12679496/10622825/c2506d06-773e-11e5-81e3-7ac00c0733fa.png)

![screenshot_20151020_152358](https://cloud.githubusercontent.com/assets/12679496/10622832/c79896c6-773e-11e5-881f-e8e13b906ea1.png)

**Comment by bobombolo** [comment]
antialiasing on the biome boundaries is an issue if using photoshop

**Comment by Tank-ACiD** [comment]
nice, working on generating the gis data now. also, i don't think the
real-world use will have biomes so to speak, more like "land use/land
cover".

Ryan

**Comment by bobombolo** [comment]
biomes is landcover for our purposes... I'm not using any existing "biome" code to build it. I have automatic map deletion for resetting working too, at least for singleplayer... I don't think the mapgen settings tool I am building will be used much once multiple players are in the world but I am going to implement it anyway.

**Comment by bobombolo** [comment]
do you anticipate individual tree placement or more of a density / maturity index? I know that individual trees are considered site "artefacts" for aboriginal archaeology if the tree has been modified

**Comment by bobombolo** [comment]
I wonder if we would want to be able to load landsat style color imagery. if so we can approximate the color like this mod does: https://forum.minetest.net/viewtopic.php?id=6751 (ImageLoader)

best fit function: https://github.com/kaeza/minetest-imageloader/blob/master/palette.lua

**Comment by Tank-ACiD** [comment]
most likely a density/maturity index. lu/lc is one of many basic land cover
types, which is limited in minetest also. We could come up with 'biome'
terrain definitions to match a basic set of land cover types set by the
USGS etc.

My study area at 1m resoultion is ~ 16k x 20k pixels...is that too big to
use as a test landscape? Should I clip it down? This is actually clipped
down to achieve a delta elevation of less than 256, but I can keep the
values actual (1881 - 2431m) to test 16bit compliance. Right now I'm
delineating the river network, then I'll try to expand it to neighboring
cells at the parts which have a higher accumulation in order to better
represent the actual width. 1 voxel is good enough for little streams, but
I know for a fact that it gets at least 3m wide at a point downstream. Of
course my river network isn't exact...the highest resolution I have is 30m,
so I interpolated to 1m, but then the fill dem command will case some
'straightening' of the channel, resulting in an interpolated, approximation
of the river's actual location. Next time I'm down I'll have to get my gps
and traverse the entire main river channel to get a more accurate
representation...or spend some time digitizing it if I can find a masters
student to do the work. I'll also manually go in and delineate the two dam
bodies.

I'll also have to spend a little time digitizing the few roads..hope to get
this all to you tonight, but again just let me know what size landscape you
think were better off with testing against

Ryan

**Comment by bobombolo** [comment]
the water is kind of unruly anyway so unless you want to use blue wool so it doesn't move let's just see how what you have works for now. as long as all the rasters are the same resolution we should be fine. I use huge dem tiles and they work fine since no image is loaded into memory so I wouldn't worry about size. yes biomes that match the USGS raster indexes would work well.

**Comment by bobombolo** [comment]
should probably use https://github.com/VanessaE/plantlife_modpack (plants_lib) to do biomes and tree/shrub placement

**Comment by bobombolo** [comment]
an excellent parallel to "biomes" and more interesting than USGS landcover classification is the idea of BioGeoClimatic Zones such as those used in BC https://www.for.gov.bc.ca/hfd/library/documents/treebook/biogeo/biogeo.htm
each region has different possible zones, so there are potentially a great many of them, but in BC for example there are 17, a manageable number. However for the average map size or study area there are probably too few zones present to be useful, and then maybe USGS landcover / landuse is more interesting.

**Comment by bobombolo** [comment]
biome configuration should take place in the remote, on a separate form, allowing the user to set the break-values (grayscale values) and the cover node types and tree types for each. here is the form thus far:

![screenshot_20151025_084549](https://cloud.githubusercontent.com/assets/12679496/10716395/ea2ea568-7af4-11e5-8883-09893b8006a0.png)

**Comment by bobombolo** [comment]
![screenshot_20151025_092420](https://cloud.githubusercontent.com/assets/12679496/10716556/3d15de18-7afa-11e5-9ba1-5370589a4840.png)

**Comment by Tank-ACiD** [comment]
Need to be able to support at least 20+ unique values. USGS lulc uses 21,
not sure how many Canada uses. Might also want to use to display
soil/geology types 'at surface'

~20 US Dominant Soil orders
http://landcover.usgs.gov/

15 global soil regions
http://www.nrcs.usda.gov/wps/portal/nrcs/main/soils/survey/class/taxonomy/
see: Soil Taxonomy PDF, map at end of document

**Comment by bobombolo** [comment]
ok. i will clean the form up to make room. currently it looks like:

![screenshot_20151025_175622](https://cloud.githubusercontent.com/assets/12679496/10719210/bcf3d968-7b41-11e5-8cb3-467de91c88fc.png)


also, although there are 21 usgs lulc classes, how many of them are used in your study area?

**Comment by Tank-ACiD** [comment]
not that many, but if someone wants to generate the Earth in realterrain,
we should support the maximum amount of diversity present in "real" terrain
:) eh?

Also, there may be other uses that people will want, for example: US cities
have a classification for property types. So, if you are showing the
terrain of a city, you might want to show what properties are of what types
for doing GIS analysis. I'm not sure how many property types there are, but
surely more than 10.

Each land use /land classification will be unique to the analyst's needs,
and will be limited by the inherent number of minetest block types.

**Comment by Tank-ACiD** [comment]
can we keep the extent outside of biomes void of trees? Maybe use something
silly like nyan cat etc for nodes?

**Comment by Tank-ACiD** [comment]
seem to be a little off at the moment. I set the cutoff to 1,2,3,..10
my biome raster has values ranging from 1-10 (with one row i now see with a value of 127, hence the error at the N edge..must be a NULL row that was converted to the value 127)

basically I would suggest converting the individual variables into tables, at the least a table for each setting, or a nested table for each of the biome settings.

code: need to set the biome, water, road raster value to node type assignment absolute, not <=. This way all the nodes that are not a biome (outside of the real world) can be set to something like wool:yellow. If we add
ground = minetest.get_content_id("wool:yellow")
before the big biome if-else tree, anything not a biome will default to that. I would also suggest adding this default to the biome menu, so the user can set the 'ground' to distinguish it from the realterrain.

I'm still not too familiar with collaborating code trees, forking etc on github..I've only every used cvs as version control. Let me know how you'd like me to handle code changes like my augmentation of function realterrain.list_images(), etc :)

**Comment by bobombolo** [comment]
dropdowns added for node types, filtered appropriately.

tableifying of biome settings moved to issue #34 

biome 0 is now editable in the form
