### ISSUE TITLE
gm processor

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#90]
the beauty of graphicsmagic is that it handles the arcmap created 16 bit dems out of the box... maybe it has hi dynamic range images turned on by default so it can handle float pixel values and negative values...

getting the build_heightmap() function sorted out would get this library to be an option, (although getting the single pixel value for get_surface() would still require a costly crop to 1x1 -- costly on very large rasters)

**Comment by Tank-ACiD** [comment]
installing it now, will take a gander

**Comment by bobombolo** [comment]
gm and gm convert are returning the entire image as an enumeration sometimes, I think that may be its behaviour when the crop is completely off the raster or something. anyway, i think fixing the alignment geometry will stop this from happening, I hope.
