### ISSUE TITLE
scaling smoothly

### ISSUE THREAD

**Issue by bobombolo** [bobombolo/realterrain#93]
now that build_heightmap is working, we could look at doing some smoothing when scaling...
that could be done implicitly by resizing the cropped image in convert or gm or magick mode... or it could be done explicitly by taking the weighted average of a neighborhood. of course this would be for the elevation raster only, or at any rate, NOT the cover/biome raster...

**Comment by bobombolo** [comment]
not smoothed
![screenshot_20151223_094523](https://cloud.githubusercontent.com/assets/12679496/11981735/20a5af04-a95a-11e5-9dfd-0f37c8ae935d.png)
first attempt at smoothing, not sure why biomes are wrong
![screenshot_20151223_094439](https://cloud.githubusercontent.com/assets/12679496/11981745/330f7daa-a95a-11e5-9364-673778b446a0.png)
code:
<pre>
if rastername == "elev" and (xscale ~= 1 or zscale ~= 1) then
									local avg = 0
									local count = 0
									for j=-1,1 do
										for i=-1,1 do
											if pixels[newz+j] and pixels[newz+j][newx+i] then
												count = count +1
												avg = avg + pixels[newz+j][newx+i]
											end
										end
									end
									avg = avg/count
									heightmap[z][x][rastername] = avg
								else
									heightmap[z][x][rastername] = pixels[newz][newx]
								end
</pre>

**Comment by Tank-ACiD** [comment]
the sampling/smoothing in gis software is already pretty robust...

**Comment by bobombolo** [comment]
so that was a rounding error. anyway, taking the average of the surrounding pixels seems to have zero effect.
![screenshot_20151223_095353](https://cloud.githubusercontent.com/assets/12679496/11982095/3778e02c-a95d-11e5-9a5b-4eec5150d48c.png)

**Comment by bobombolo** [comment]
yeah i don't know if i care about this. people can smooth with GIS tools if they want it that bad. or graphics software

**Comment by bobombolo** [comment]
mostly i was trying to humour this post: https://forum.minetest.net/viewtopic.php?f=11&t=12666&start=25#p202203
