### ISSUE TITLE
no way to set file bit depth

### ISSUE THREAD

**Issue by Tank-ACiD** [bobombolo/realterrain#99]
the in-game menu tool no longer lets you select the bit depth. for now I have to manually edit the init.lua code when using 16bit, as it hard defaults to 8

**Comment by bobombolo** [comment]
bit depth is autodetected in several modes now, editing the lua file manually probably won't matter because in those modes the manual setting for bit depth is ignored. changing the MAGICK_AS_CONVERT to false will reveal this setting again. for the normal use of imlib2 or lua-magick libs
